mindspore-lab/mindone

examples/stable_diffusion_v2/requirements.txt

Add tqdm package for user friendly.

Add missing requirement package.

---

examples/stable_diffusion_v2/ldm/modules/encoders/text_encoder.py
examples/stable_diffusion_v2/text_to_image.py
examples/stable_diffusion_v2/utils/model_utils.py

1. Validator not exsit in ms2.0
2. Tensor data type inconsist
Optimize codes:
1. change ms context mode to static variable

Fix bugs (MS2.0/Ascend/Inference)

---

examples/stable_diffusion_v2/text_to_image.py

The message does not consist with context.

Fix codes: error message.

---

examples/stable_diffusion_v2/README.md
examples/stable_diffusion_v2/configs/train_dreambooth_sd_v2.json
examples/stable_diffusion_v2/configs/train_dreambooth_sd_v2.yaml
examples/stable_diffusion_v2/dreambooth_finetune.md
examples/stable_diffusion_v2/ldm/data/dataset_db.py
examples/stable_diffusion_v2/ldm/data/t2i_collate.py
examples/stable_diffusion_v2/ldm/models/diffusion/ddim.py
examples/stable_diffusion_v2/ldm/models/diffusion/ddpm.py
examples/stable_diffusion_v2/ldm/modules/train/callback.py
examples/stable_diffusion_v2/ldm/util.py
examples/stable_diffusion_v2/scripts/run_train_dreambooth_sd_v2.sh
examples/stable_diffusion_v2/text_to_image.py
examples/stable_diffusion_v2/train_dreambooth.py

Train dreambooth and inference. I created `LatentDiffusionDreamBooth` instead of using `LatentDiffusionDB` because `LatentDiffusionDB` rewrites many functions.

dreambooth updates

---

examples/stable_diffusion_v2/ldm/modules/train/ema.py
examples/stable_diffusion_v2/train_text_to_image.py

修复使用ema训练时内存不足的bug.
修复当decay_steps<=0时报错的问题，修改后当decay_steps<=0时会强制将decay_steps设置为1并给出warning

Fix allocate memory failed bug during ema training and bug when decay_step is less than or equal to 0

---

examples/stable_diffusion_v2/ldm/modules/train/callback.py

remove `self.lora_rank=None` and use `self.use_lora = use_lora`

fix callback self.use_lora bug

---

examples/stable_diffusion_v2/scripts/run_text_to_image_v2_v_pred.sh
examples/stable_diffusion_v2/scripts/run_train_v2_v_pred.sh
examples/stable_diffusion_v2/text_to_image.py
examples/stable_diffusion_v2/v_prediction.md

1. add v-prediction readme doc
2. add v-prediction script
3. fix some bugs of sampling

update v-prediction assessment including code and doc

---

examples/stable_diffusion_v2/ldm/modules/train/callback.py
examples/stable_diffusion_v2/ldm/modules/train/checkpoint.py
examples/stable_diffusion_v2/train_text_to_image.py

When training is interrupted, the resume training function can be used to continue training from the interrupted point.
For use this function, you can set the parameter `resume` is True or path to resume checkpoint.

add resume training

---

examples/stable_diffusion_v2/tests/st/_common.py
examples/stable_diffusion_v2/tests/st/dummy_labels/img_txt.csv
examples/stable_diffusion_v2/tests/st/test_train_eval_dummy.py
examples/stable_diffusion_v2/tests/st/test_train_infer.md
examples/stable_diffusion_v2/tests/st/test_train_infer_dummy.py

运行命令：pytest tests/st/test_train_infer_dummy.py

Add ST for train and infer

---

examples/stable_diffusion_v2/train_dreambooth.py

In dreambooth, tokenize the prompts list before running `get_learned_conditioning`, just like #73

[DreamBooth] adapt 910B eval

---

examples/stable_diffusion_v2/dreambooth_finetune.md
examples/stable_diffusion_v2/lora_finetune.md

fix issue: https://github.com/mindspore-lab/mindone/issues/96

fix eval path

---

examples/stable_diffusion_v2/ldm/modules/train/callback.py
examples/stable_diffusion_v2/ldm/modules/train/dynamic_lr.py
examples/stable_diffusion_v2/ldm/modules/train/learningrate.py
examples/stable_diffusion_v2/ldm/modules/train/lr_schedule.py
examples/stable_diffusion_v2/ldm/modules/train/recorder.py
examples/stable_diffusion_v2/train_text_to_image.py

add lr scheduler: "constant", "cosine_decay", "polynomial_decay", "multi_step_decay".

update lr scheduler

---

examples/stable_diffusion_v2/configs/train_config_v2.1_base.json
examples/stable_diffusion_v2/ldm/data/dataset.py
examples/stable_diffusion_v2/ldm/data/dataset_db.py
examples/stable_diffusion_v2/ldm/data/dataset_dist.py
examples/stable_diffusion_v2/ldm/data/sync_data.py
examples/stable_diffusion_v2/tests/test_lora.py
examples/stable_diffusion_v2/tools/data_utils/data_check_part.py
examples/stable_diffusion_v2/tools/data_utils/generate_num_samples.py
examples/stable_diffusion_v2/tools/data_utils/laion_gen_csv_annot.py
examples/stable_diffusion_v2/train_text_to_image.py

Motivation:
1. Upload the training codes from the ModelArt platform;
2. Combining Luoyang's codes with the latest codes;
3. Add data check codes.

Add modelarts's training codes

---

examples/stable_diffusion_v2/ldm/modules/attention.py

Motivation:
1. tiling strategy "xunfei" is not supported in ms2.1 release version, only "sparse" and "wukong" are supported;
Test plan:
Already tested in ModelArts platform.

Fix flash attention for ms2.1

---

examples/stable_diffusion_v2/dreambooth_finetune.md
examples/stable_diffusion_v2/scripts/run_train_dreambooth_sd_v2.sh

update DB readme

---

examples/stable_diffusion_v2/README.md

1. Clarified T2I-Adapter docs
2. Fixed some issues in SD's Readme (second commit)

clarify T2I-Adapter docs

---

examples/stable_diffusion_v2/train_dreambooth.py

Fix the bug in this issue #143

fix dreambooth+lora trainable param bug

---

examples/stable_diffusion_v2/ldm/modules/train/callback.py
examples/stable_diffusion_v2/ldm/modules/train/trainer.py
examples/videocomposer/README.md
examples/videocomposer/configs/train.yaml
examples/videocomposer/configs/train_base.py
examples/videocomposer/train.py

910b bugs (on MS master 0919): no more in-graph print
checkpoint saving name: sd-{epoch}.ckpt -> vc_unet-{epoch}.ckpt
gradient accumulation can be set via configs/train_base.py

Fix 910b bugs (on MS master 0919); Allow grad accumulation setting; Fix checkpoint saving name

---

examples/videocomposer/configs/train_base.py
examples/videocomposer/run_train.sh
examples/videocomposer/run_train_distribute.sh
examples/videocomposer/train.py
examples/videocomposer/vc/config/parser.py

Now the configuration definition logic is: (1) load the yaml file, and update the arguments if the arguments given by command are not None or set by default; (2) load the `configs/train_base.py`, and update it given the configurations defined in (1).

Improve VideoComposer Training

---

examples/stable_diffusion_xl/demo/streamlit_helpers.py
examples/stable_diffusion_xl/gm/helpers.py
examples/stable_diffusion_xl/gm/modules/diffusionmodules/sampler.py
examples/stable_diffusion_xl/gm/modules/diffusionmodules/sampling_utils.py

add HeunEDMSampler, DPMPP2MSampler

feat: add sdxl sampler

---

examples/videocomposer/vc/data/transforms.py

Change the center crop function in ms transforms to achieve better alignment with torch transforms. This commit is verified to work properly with the training script.
@zhtmike  need to verify and change the ms transforms in infer and deploy folders as well.

Videocomposer: update CenterCrop for alignment

---

examples/videocomposer/vc/diffusion/latent_diffusion.py

Fix a bug related to vae encode data rearragement.

vae after encode data rearrange

---

examples/videocomposer/deploy/data/transforms.py
examples/videocomposer/deploy/modules/builder.py
examples/videocomposer/vc/data/transforms.py
examples/videocomposer/vc/infer_engine/modules/builder.py

[VC] sync with train transform

---

examples/videocomposer/vc/data/dataset_train.py
examples/videocomposer/vc/data/datasets.py

- add dirty data filtering to `vc/data/datasets.py` for inference part
- update filtering way to fix bug

[VC] Update dirty data filtering to avoid potential bug

---

examples/videocomposer/configs/train_exp02_motion_transfer.yaml
examples/videocomposer/run_motion_transfer.sh
examples/videocomposer/run_train_distribute.sh
examples/videocomposer/vc/data/transforms.py
examples/videocomposer/vc/models/clip_embedder.py
examples/videocomposer/vc/models/droppath.py
examples/videocomposer/vc/models/rotary_embedding.py
examples/videocomposer/vc/models/unet_sd.py

Env: 910B + CANN 7.0-T2 + MS2.2-0907 version
cmd: 
bash run_train_distribute.sh
Key setting:
recompute: ON
Note that: theses change may not be the reason leading to the successful run on 910B. The correct CANN version and MS2.2 can be the real game changer.

910B parallel training and finetune ok version: rm assert and enable REF mode in infer

---

examples/videocomposer/configs/train_exp05_text_depths_wo_style.yaml
examples/videocomposer/run_text_depths_wo_style.sh

Train exp05 training and inference shell scripts. The inference performance is good on ms2.2 0907.

videocomposer: train exp05

---

examples/videocomposer/README.md
examples/videocomposer/requirements.txt
examples/videocomposer/tools/data_converter.py
examples/videocomposer/tools/gen_frames.py
examples/videocomposer/tools/webvid_scripts/datacheck_webvid.py
examples/videocomposer/tools/webvid_scripts/divide_parts.py
examples/videocomposer/tools/webvid_scripts/download_webvid.sh
examples/videocomposer/tools/webvid_scripts/ecs2local.sh

Add scripts for converting videocomposer training data to the desired format, generating video frames offline, and downloading and processing webvid-10m dataset.

[VC] add data converter, generate video frames, webvid-10m processing scripts, etc.

---

examples/stable_diffusion_xl/inference/README.md
examples/stable_diffusion_xl/inference/config/lite/sd_lite.cfg
examples/stable_diffusion_xl/inference/config/model/sd_xl_base_inference.yaml
examples/stable_diffusion_xl/inference/config/schedule/euler_edm.yaml
examples/stable_diffusion_xl/inference/config/text2img.yaml
examples/stable_diffusion_xl/inference/export.py
examples/stable_diffusion_xl/inference/libs/helper.py
examples/stable_diffusion_xl/inference/libs/infer_engine/export_modules.py
examples/stable_diffusion_xl/inference/libs/infer_engine/model_base.py
examples/stable_diffusion_xl/inference/libs/infer_engine/sd_lite_models.py
examples/stable_diffusion_xl/inference/libs/logger.py
examples/stable_diffusion_xl/inference/libs/scheduler/euler_edm_sampler.py
examples/stable_diffusion_xl/inference/libs/sd_models.py
examples/stable_diffusion_xl/inference/libs/tokenizer.py
examples/stable_diffusion_xl/inference/libs/util.py
examples/stable_diffusion_xl/inference/sd_infer.py
examples/stable_diffusion_xl/inference/sd_lite_infer.py

* sdxl model export to lite 
*  sdxl model lite infer

[feat] add sdxl-lite inference

---

examples/videocomposer/tools/modelarts_adapter/common.py
examples/videocomposer/tools/modelarts_adapter/fmk.py
examples/videocomposer/tools/modelarts_adapter/manager.py
examples/videocomposer/tools/modelarts_adapter/rank_table.py
examples/videocomposer/tools/modelarts_adapter/run_ascend.py

modelarts多机多卡训练跑通配置文件。
放在`examples/videocomposer/`目录下，注意`run_ascend.py`中的`RankTableTemplate1`和`RankTableTemplate2`。
Reference: https://support.huaweicloud.com/bestpractice-modelarts/develop-modelarts-0120.html

[VC] config files for distribtued training on multi devices on modelarts

---

examples/stable_diffusion_xl/offline_inference/libs/sd_models.py

[fix] fix sdxl-ckpt inference

---

examples/stable_diffusion_xl/gm/modules/embedders/open_clip/transformer.py
examples/stable_diffusion_xl/gm/modules/transformers/activations.py

clip: nn.GELU -> QuickGELU, relative diff: 7% -> 0.1%
openclip(penultimate): norm_layer-eps default1e-7 -> 1e-5, diff relative: 4.8% -> 0.6%
openclip(pool): norm_layer-eps default1e-7 -> 1e-5, diff relative: 700% -> 0.7%

fix: correct differences with source code in clip and open_clip

---

examples/stable_diffusion_xl/gm/models/trainer_factory.py
examples/stable_diffusion_xl/train.py

1. add clip score
2. fix gradient accumulation bug :  accumulated_grad = accumulated_grad  + grads  ——>  accumulated_grad = accumulated_grad + grads / accum_steps

SDXL: fix gradient accumulation bug and add clip grad in graph mode

---

examples/stable_diffusion_xl/offline_inference/config/model/sd_xl_base_inference.yaml
examples/stable_diffusion_xl/offline_inference/export.py
examples/stable_diffusion_xl/offline_inference/libs/infer_engine/export_modules.py
examples/stable_diffusion_xl/offline_inference/libs/infer_engine/sd_lite_models.py
examples/stable_diffusion_xl/offline_inference/libs/sd_models.py
examples/stable_diffusion_xl/offline_inference/sd_infer.py

[fix] fix sdxl lite precision

---

examples/stable_diffusion_xl/gm/helpers.py
examples/stable_diffusion_xl/modelarts/common.py
examples/stable_diffusion_xl/modelarts/fmk.py
examples/stable_diffusion_xl/modelarts/manager.py
examples/stable_diffusion_xl/modelarts/rank_table.py
examples/stable_diffusion_xl/modelarts/run_ascend.py

1、已知限制场景：在设置mode为图模式存在单算子broadcast，hccl会初始化失败
2、增加云上多机运行的依赖脚本

Fixed an error in graph mode for single-operator broadcast.

---

examples/stable_diffusion_xl/GETTING_STARTED.md
examples/stable_diffusion_xl/offline_inference/README.md
examples/stable_diffusion_xl/tools/model_conversion/README.md
examples/stable_diffusion_xl/tools/model_conversion/convert_weight.py
examples/stable_diffusion_xl/tools/model_conversion/merge_lora_to_base.py
examples/stable_diffusion_xl/weight_convertion.md

Add model conversion from MS to PT.
Add dreambooth via lora conversion example.
Adapt to conversions of Vallina for the offical SDXL torch repo as well.

Add model conversion from MS to PT

---

examples/pangu_draw_v3/README.md
examples/pangu_draw_v3/README_CN.md

1. Add PanGu-Draw-v3 pretrained weights in README.md
2. Modify the minumum version of dependent libraries MindSpore

[PanGu] Add Pretrained Weights

---

examples/stable_diffusion_xl/gm/modules/attention.py

SD-XL: change data type to make flash attention in sd_xl available on 910B & MS2.2.10

---

examples/stable_diffusion_xl/configs/training/sd_xl_base_finetune_lora_910a.yaml
examples/stable_diffusion_xl/configs/training/sd_xl_base_finetune_lora_910b.yaml

because use auto_mixed_precision interface, lora finetune need update config yaml

update sdxl lora config yaml

---

examples/stable_diffusion_xl/gm/modules/attention.py
examples/svd/configs/svd.yaml
examples/svd/modules/temporal_ae.py
examples/svd/modules/unet3d.py

Adding support for Flash Attention in SVD, as FA was integrated into SDXL in PR #264.

add FA support in SVD

---

examples/stable_diffusion_xl/gm/data/dataset.py
examples/stable_diffusion_xl/gm/data/dataset_wds.py
examples/stable_diffusion_xl/gm/helpers.py
examples/stable_diffusion_xl/train.py

1. scale learning rate by global batch size, reference: https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_sdxl.py#L313
2. set prompts empty randomly, reference: https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_sdxl.py#L219

Scale lr & empty prompt

---

examples/stable_diffusion_v2/README.md
examples/stable_diffusion_v2/common.py
examples/stable_diffusion_v2/text_to_image.py

Parallel can be use for mutil prompts

sdv2: Parallel for text_to_image

---

examples/ip_adapter/README.md
examples/ip_adapter/controlnet_sdxl.py
examples/ip_adapter/image_variation_sdxl.py
examples/stable_diffusion_v2/benchmark.md
examples/stable_diffusion_v2/ldm/modules/train/optim.py
mindone/trainers/optim.py

1. fix the bug when num_trials > 1 in IPAdapter inference code
2. fix the training optim for sd1.5 when group strategy is none

Add IPAdapter benchmark and fix several bugs

---

examples/stable_diffusion_xl/GETTING_STARTED.md
examples/stable_diffusion_xl/gm/data/dataset.py
examples/stable_diffusion_xl/gm/data/loader.py
examples/stable_diffusion_xl/gm/helpers.py
examples/stable_diffusion_xl/gm/models/diffusion.py
examples/stable_diffusion_xl/gm/modules/embedders/modules.py
examples/stable_diffusion_xl/gm/modules/embedders/open_clip/__init__.py
examples/stable_diffusion_xl/gm/modules/embedders/open_clip/tokenizer.py
examples/stable_diffusion_xl/gm/util/util.py
examples/stable_diffusion_xl/train.py

1. add get_text_index, lpw_openclip_tokenize, pad_tokens, pre compile graph
2. update embedding
3. add the parameter --lpw True to use long prompts training

SD-XL: Add support for long prompts training

---

.github/PULL_REQUEST_TEMPLATE.md

Adds Pull Request Template for better PR review and management
@zhanghuiyao 
@geniuspatrick 
@vigo999 
@hadipash

Adds Pull Request Template 

---

examples/stable_diffusion_xl/gm/models/trainer_factory.py
examples/stable_diffusion_xl/train.py

add timestep bias strategies when training.

sdxl: add timestep bias strategies

---

examples/stable_diffusion_v2/tests/st/get_tested.md
examples/stable_diffusion_v2/tests/st/test_overfit.py
examples/stable_diffusion_v2/train_dreambooth.py

1. This #311 modified the path of the result.log in the callback. Need modify test_overfit.py code
2. update test_overfilt.py to reduce runtime

sdv2: Fixed test code bug and update code to reduce runtime

---

examples/stable_diffusion_xl/gm/models/trainer_factory.py
examples/stable_diffusion_xl/gm/util/util.py
examples/stable_diffusion_xl/train.py
examples/stable_diffusion_xl/vanilla_finetune.md

fix timestep bias weighting bug
@xxx

fix timestep bias weighting strategy

---

examples/stable_diffusion_xl/gm/data/dataset_wds.py
examples/stable_diffusion_xl/gm/modules/embedders/modules.py

Fixes some problems about interface compatibility

Fixes: SD XL interface compatibility

---

examples/stable_diffusion_xl/tools/model_conversion/convert_weight.py

fix convert_weight.py‘s bug

---

examples/stable_diffusion_v2/convert_dataset.py
examples/stable_diffusion_xl/GETTING_STARTED.md
examples/stable_diffusion_xl/configs/training/sd_xl_base_finetune_910b_wds.yaml
examples/stable_diffusion_xl/configs/training/sd_xl_base_finetune_910b_wids.yaml
examples/stable_diffusion_xl/gm/data/dataset_wds.py
examples/stable_diffusion_xl/gm/data/loader.py
examples/stable_diffusion_xl/requirement.txt
examples/stable_diffusion_xl/tests/test_loader.py

Webdataset training for SDXL
@xxx

Add origin webdataset support

---

examples/stable_diffusion_v2/benchmark.md
examples/stable_diffusion_v2/inference/config/model/v2-vpred-inference.yaml
examples/stable_diffusion_v2/inference/config/text2img.yaml

Update the benchmark for sd inference.
Use inference/sd_infer.py to test performance.
@xxx

SDV2: update sdv2 benchmarking

---

examples/stable_diffusion_xl/GETTING_STARTED.md
examples/stable_diffusion_xl/README.md
examples/stable_diffusion_xl/lora_finetune.md

SDXL: update sdxl lora benchmarking

---

examples/animatediff/README.md
examples/animatediff/ad/data/dataset.py
examples/animatediff/ad/models/diffusion/ddpm.py
examples/animatediff/args_train.py
examples/animatediff/configs/stable_diffusion/v1-train-mmv2-cache.yaml
examples/animatediff/configs/training/mmv2_train_cache.yaml
examples/animatediff/scripts/run_mmv2_train_cache.sh
examples/animatediff/tools/README.md
examples/animatediff/tools/embedding_cache.py
examples/animatediff/train.py

Add support of dataset embedding cache for Animatediff training

---

examples/stable_diffusion_xl/gm/helpers.py

Fixes #307 
skip cache args checking for dreambooth training.
@SamitHuang @zhanghuiyao

fix: skip cache args checking for dreambooth training

---

examples/stable_diffusion_xl/gm/data/loader.py

num_parallel_worker setting bug
@xxx

sdxl: fix num_parallel_worker setting bug

---

examples/stable_diffusion_xl/gm/data/loader.py
examples/stable_diffusion_xl/gm/helpers.py
examples/stable_diffusion_xl/train.py

Adds # (feature) use `num_epochs` to set dataloader in training
@everyone

SDXL: use `num_epochs` to set dataloader

---

examples/stable_diffusion_xl/gm/data/dataset.py
examples/stable_diffusion_xl/gm/data/dataset_wds.py
examples/stable_diffusion_xl/gm/data/util.py

sdxl: add dataset type check

---

examples/stable_diffusion_xl/train.py
examples/stable_diffusion_xl/vanilla_finetune.md

resume training from a specified training step
@xxx

SDXL: resume from specified training step

---

examples/stable_diffusion_xl/gm/lr_scheduler.py

sdxl: Add warmup lr

---

examples/stable_diffusion_xl/gm/data/loader.py

fix import

---

mindone/utils/modelarts/README.md
mindone/utils/modelarts/common.py
mindone/utils/modelarts/fmk.py
mindone/utils/modelarts/manager.py
mindone/utils/modelarts/rank_table.py
mindone/utils/modelarts/run_ascend.py

Add scripts ( as common module in `mindone/utils/modelarts`) for launching distributed training on modelarts. Refer to [here](https://support.huaweicloud.com/bestpractice-modelarts/develop-modelarts-0120.html).

Add scripts for launching distributed training on modelarts

---

examples/stable_diffusion_v2/ldm/modules/attention.py

Fixes # Flash attention API changed in ms2.3
@SamitHuang @CaitinZhao

Fix sd v2 flash attention for ms2.3

---

examples/animatediff/ad/data/dataset.py
examples/animatediff/ad/modules/attention.py
examples/animatediff/ad/modules/diffusionmodules/unet3d.py
examples/animatediff/args_train.py
examples/animatediff/scripts/run_mmv2_train_512_webvid5.sh
examples/animatediff/train.py
mindone/trainers/checkpoint.py
mindone/utils/amp.py

Add video flip option and adapt to modelart

---

examples/animatediff/ad/data/dataset.py
examples/animatediff/train.py

Fix path args

---

examples/animatediff/ad/data/dataset.py
examples/animatediff/args_train.py
examples/animatediff/configs/stable_diffusion/v1-train-mmv2.yaml
examples/animatediff/scripts/run_mmv2_train_512_webvid5.sh
examples/animatediff/tests/test_data.py
examples/animatediff/train.py
examples/stable_diffusion_xl/gm/models/trainer_factory.py

Data format and vae precision adaptation for AD

---

examples/animatediff/text_to_video.py

Can be used to compare our inference result with others'

Animatediff: support loading init latent noise file to infer

---

examples/stable_diffusion_xl/gm/helpers.py
examples/stable_diffusion_xl/train_dreambooth.py

Fixes #323 
pr323 concated multi-samples from a prompt for inference using a loop and the input of perform_save_locally must be a list. but the infer_during_train function of other training scripts did not turn the output of do_sample to a list and directly pass to the perform_save_locally api.
@SamitHuang @zhanghuiyao

sdxl: fix perform_save_locally api

---

examples/stable_diffusion_xl/gm/data/dataset.py
examples/stable_diffusion_xl/gm/data/mappers/sample_mappers.py
examples/stable_diffusion_xl/tools/rank_table_generation/README.md
examples/stable_diffusion_xl/tools/rank_table_generation/merge_hccl.py
examples/stable_diffusion_xl/train.py

1. record `crop_coords_top_left` of images in data preprocessing class `CenterCrop`
Adds # (feature) SDXL: Some features used in customized version
1. support `save_path` for `merge_hccl.py`
2. support saving ckpt only on rank0
3. shrink large images before other data preprocessing operations
P.S. These changes have been verified in customer‘s experiments.
@xxx

SDXL: Some features used in customized version

---

examples/stable_diffusion_xl/configs/training/sd_xl_base_finetune_dreambooth_lora_910a.yaml
examples/stable_diffusion_xl/configs/training/sd_xl_base_finetune_dreambooth_lora_910b.yaml
examples/stable_diffusion_xl/configs/training/sd_xl_base_finetune_dreambooth_textencoder_lora_910b.yaml
examples/stable_diffusion_xl/demo/sampling_without_streamlit.py
examples/stable_diffusion_xl/gm/helpers.py
examples/stable_diffusion_xl/gm/modules/diffusionmodules/guiders.py
examples/stable_diffusion_xl/gm/modules/diffusionmodules/sampler.py
examples/stable_diffusion_xl/gm/modules/diffusionmodules/sampling_utils.py
examples/stable_diffusion_xl/gm/util/util.py
examples/stable_diffusion_xl/inference.md

Usage of EDMDiscretization: 
=======**Example ① EDMEulerScheduler**=======
directly set the following args in `sampling_without_streamlit.py`:
```shell
--sampler EulerEDMSampler
--discretization EDMDiscretization 
--sigma_min 0.002
--sigma_max 80.0
--rho 7.0
```
**or** 
set `--sampler EulerEDMSampler` in `sampling_without_streamlit.py`
and set discretization_config as follows in denoiser_config of `examples/stable_diffusion_xl/configs/inference/sd_xl_base.yaml`
```shell
...
discretization_config:
target: gm.modules.diffusionmodules.discretizer.EDMDiscretization
params:
sigma_min: 0.02
sigma_max: 80.0
rho: 7.0
```
=======**Example ② EDMDPMSolverMultistepScheduler**=======
directly  set the following args in `sampling_without_streamlit.py`:
```shell
--sampler DPMPP2MSampler  #dpm++ 2nd …
```

sdxl: configure edm inference and dynamic thresholding

---

examples/stable_diffusion_xl/gm/modules/attention.py
examples/stable_diffusion_xl/gm/modules/diffusionmodules/denoiser_scaling.py
examples/stable_diffusion_xl/gm/modules/diffusionmodules/model.py
examples/stable_diffusion_xl/gm/modules/diffusionmodules/sampler.py
examples/stable_diffusion_xl/gm/modules/embedders/clip/modeling_clip.py
examples/stable_diffusion_xl/gm/modules/lora/layers.py
examples/stable_diffusion_xl/gm/util/util.py
examples/stable_diffusion_xl/train.py
examples/stable_diffusion_xl/train_dreambooth.py

Adapt to ms2.3 GE, including changes of the interface of FA, mixed-precision, etc. 
@xxx

adapt to ms2.3 GE

---

examples/stable_diffusion_xl/gm/data/dataset_wds.py

sdxl: add lpw training on webdataset/wids

---

examples/stable_diffusion_xl/gm/data/loader.py
examples/stable_diffusion_xl/gm/helpers.py
examples/stable_diffusion_xl/scripts/cache_data.sh
examples/stable_diffusion_xl/train.py
examples/stable_diffusion_xl/vanilla_finetune.md

sdxl: fix cache bug

---

examples/animatediff/README.md
examples/animatediff/ad/models/autoencoder.py
examples/animatediff/ad/models/diffusion/ddpm.py
examples/animatediff/ad/modules/attention.py
examples/animatediff/ad/modules/diffusionmodules/openaimodel.py
examples/animatediff/ad/modules/diffusionmodules/unet3d.py
examples/animatediff/args_train.py
examples/animatediff/configs/stable_diffusion/v1-inference-mmv1.yaml
examples/animatediff/configs/stable_diffusion/v1-inference-mmv2.yaml
examples/animatediff/configs/stable_diffusion/v1-train-mmv2.yaml
examples/animatediff/configs/training/mmv2_finetune_512.yaml
examples/animatediff/scripts/run_mmv2_finetune_512.sh
examples/animatediff/scripts/run_mmv2_train_512_webvid5.sh
examples/animatediff/scripts/run_mmv2_train_gpu.sh
examples/animatediff/train.py

Add min-snr weighting to improve AD training && Support any-shape infer

---

mindone/models/latte.py
mindone/models/modules/pos_embed.py

Fix the bug of Latte model initialization: failed to initialize temporal position embedding.

Latte training bug fix: temp_embed initialization

---

examples/stable_diffusion_v2/tests/st/test_overfit.py

SDV2: fix sdv2 text_overfit bug

---

examples/stable_diffusion_xl/cldm/cldm.py
examples/stable_diffusion_xl/cldm/util.py
examples/stable_diffusion_xl/configs/inference/sd_xl_base_controlnet.yaml
examples/stable_diffusion_xl/configs/training/sd_xl_base_finetune_controlnet_910b.yaml
examples/stable_diffusion_xl/controlnet.md
examples/stable_diffusion_xl/demo/sampling_without_streamlit.py
examples/stable_diffusion_xl/gm/data/dataset.py
examples/stable_diffusion_xl/gm/data/mappers/sample_mappers.py
examples/stable_diffusion_xl/gm/helpers.py
examples/stable_diffusion_xl/gm/models/trainer_factory.py
examples/stable_diffusion_xl/scripts/run_infer_base_controlnet.sh
examples/stable_diffusion_xl/scripts/run_train_base_controlnet.sh
examples/stable_diffusion_xl/tools/controlnet_conversion/README.md
examples/stable_diffusion_xl/tools/controlnet_conversion/init_weight.py
examples/stable_diffusion_xl/train_controlnet.py

sdxl controlnet training pipeline, get satisfied training result on fill50k dataset

Training Pipeline for ControlNet + SDXL

---

examples/stable_diffusion_xl/demo/sampling_without_streamlit.py

修复refiner在出图过程中出现的sample_z字段未定义的问题
Fixes # (issue)https://github.com/mindspore-lab/mindone/issues/412
@xxx

Generate image error in refiner

---

examples/animatediff/ad/modules/attention.py
examples/svd/models/diffusion.py
mindone/models/lora.py
mindone/models/modules/flash_attention.py
mindone/utils/version_control.py

Renames `MSVersion` to `MS_VERSION` to match the [PEP 8](https://peps.python.org/pep-0008/#constants) standard for constants.
@xxx

rename `MSVersion` to match PEP 8

---

examples/svd/train.py
examples/t2i_adapter/train_t2i_adapter_sd.py
mindone/data/__init__.py
mindone/data/loader.py

This PR renames the data loader builder from `build_dataloader` to `create_dataloader` to match the naming convention used in the rest of the project, such as `create_scheduler`, `create_optimizer`, etc.
@xxx

refactor mindone's dataloader

---

examples/stable_diffusion_xl/gm/modules/attention.py

delete trace decorator that is removed in ms2.3
@xxx

delete trace decorator that is removed in ms2.3

---

examples/stable_diffusion_v2/common.py
examples/stable_diffusion_v2/train_dreambooth.py

sdv2 ms2.3: add_dvm_set_context

---

examples/stable_diffusion_v2/ldm/models/diffusion/dpm_solver/dpm_solver.py

sdv2: modify linspace for ms2.3

---

examples/stable_diffusion_v2/ldm/data/dataset_controlnet.py

sdv2 ms2.3: fix controlnet dataset tokenize bug

---

examples/stable_diffusion_xl/gm/data/dataset_wds.py

support data cache for webdataset

---

examples/stable_diffusion_v2/ldm/data/dataset.py

fix bug for sdv2 dataset shuffle
@xxx

sdv2: fix bug for sdv2 dataset shuffle

---

examples/stable_diffusion_v2/ldm/models/diffusion/dpm_solver/dpm_solver.py

master sdv2: modify linspace

---

examples/svd/svd_tools/convert.py

Fixes the SDXL module import bug described in #423 .
@xxx

fix SVD model conversion

---

examples/stable_diffusion_v2/ldm/data/dataset_controlnet.py

sdv2 master: fix controlnet dataset tokenize bug

---

examples/stable_diffusion_xl/gm/data/dataset_wds.py
examples/stable_diffusion_xl/gm/data/mappers/batched_mappers.py

sdxl: fix webdataset ranksize gather than tar files

---

examples/stable_diffusion_xl/configs/training/sd_xl_base_finetune_910b_fa.yaml
examples/stable_diffusion_xl/configs/training/sd_xl_base_finetune_unet_textencoder_910b.yaml
examples/stable_diffusion_xl/demo/sampling_without_streamlit.py
examples/stable_diffusion_xl/gm/data/dataset.py
examples/stable_diffusion_xl/gm/helpers.py
examples/stable_diffusion_xl/gm/modules/attention.py
examples/stable_diffusion_xl/gm/modules/diffusionmodules/denoiser_scaling.py
examples/stable_diffusion_xl/gm/modules/diffusionmodules/loss.py
examples/stable_diffusion_xl/gm/modules/diffusionmodules/openaimodel.py
examples/stable_diffusion_xl/gm/modules/embedders/modules.py
examples/stable_diffusion_xl/gm/modules/embedders/open_clip/__init__.py
examples/stable_diffusion_xl/gm/modules/embedders/open_clip/tokenizer.py
examples/stable_diffusion_xl/gm/modules/transformers/transformers.py
examples/stable_diffusion_xl/gm/util/util.py
examples/stable_diffusion_xl/lora_finetune.md
examples/stable_diffusion_xl/train.py
examples/stable_diffusion_xl/vanilla_finetune.md

1. update fp16 mix-precision strategy
2. adapt to diffuser lpw
3. bugfix
@xxx

sdxl: update fp16 mix-precision strategy

---

examples/stable_diffusion_v2/common.py
examples/stable_diffusion_v2/train_cldm.py
examples/stable_diffusion_v2/train_dreambooth.py
examples/stable_diffusion_v2/train_text_to_image.py

sdv2 ms2.3: add max_device_memory for ms2.3 pynative mode

---

examples/stable_diffusion_v2/common.py
examples/stable_diffusion_v2/ldm/data/dataset_controlnet.py
examples/stable_diffusion_v2/ldm/models/diffusion/dpm_solver/dpm_solver.py
examples/stable_diffusion_v2/ldm/modules/attention.py
examples/stable_diffusion_v2/train_cldm.py
examples/stable_diffusion_v2/train_dreambooth.py
examples/stable_diffusion_v2/train_text_to_image.py
examples/stable_diffusion_xl/gm/modules/attention.py
examples/stable_diffusion_xl/gm/util/util.py

Fix bug for `max_device_memory` default value.
@xxx

SDV2: Fix bug for ms2.3 branch

---

examples/stable_diffusion_xl/GETTING_STARTED.md
examples/stable_diffusion_xl/gm/data/dataset_wds.py
examples/stable_diffusion_xl/tools/data_check/get_wds_num_samples.py
examples/stable_diffusion_xl/tools/data_check/scan.py

sdxl: add data scan function

---

examples/stable_diffusion_xl/demo/sampling_without_streamlit.py

sdxl: add deterministic sampling

---

mindone/transformers/__init__.py
mindone/transformers/activations_ms.py
mindone/transformers/modeling_ms_utils.py
mindone/transformers/models/__init__.py
mindone/transformers/models/t5/__init__.py
mindone/transformers/models/t5/modeling_t5.py

The T5Model could be utilized conveniently by the following command:
from mindone.transformers.models import T5Model, T5EncoderModel
model = T5Model.from_pretrained("Google/T5-small")
encoder_model = T5EncoderModel.from_pretrained("DeepFloyd/t5-v1_1-xxl")
@xxx

T5 Encoder Model and T5 Model: Graph Mode and Pynative Mode

---

mindone/diffusers/__init__.py
mindone/diffusers/models/__init__.py
mindone/diffusers/models/embeddings.py
mindone/diffusers/pipelines/__init__.py
mindone/diffusers/pipelines/pipeline_loading_utils.py
mindone/diffusers/pipelines/pipeline_utils.py
mindone/diffusers/pipelines/stable_diffusion/__init__.py
mindone/diffusers/pipelines/stable_diffusion/pipeline_output.py
mindone/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
mindone/diffusers/pipelines/stable_diffusion/safety_checker.py
mindone/diffusers/schedulers/__init__.py
mindone/diffusers/schedulers/scheduling_pndm.py
mindone/transformers/__init__.py
mindone/transformers/models/__init__.py
mindone/transformers/models/clip/__init__.py
mindone/transformers/models/clip/modeling_ms_clip.py

feat(diffusers/sd): add stable diffusion pipeline(text to image)

---

examples/diffusers/text_to_image/train_text_to_image_sdxl.py
mindone/diffusers/models/autoencoders/autoencoder_kl.py
mindone/diffusers/models/autoencoders/vae.py
mindone/diffusers/models/modeling_utils.py
mindone/diffusers/models/transformers/transformer_2d.py
mindone/diffusers/models/unets/unet_2d_blocks.py
mindone/diffusers/models/unets/unet_2d_condition.py

feat(diffusers): support gradient checkpointing by `Cell._recompute()`

---

examples/README.md

Quick small fix

---

examples/stable_diffusion_xl/configs/training/sd_xl_base_finetune_multi_aspect.yaml
examples/stable_diffusion_xl/gm/helpers.py
examples/stable_diffusion_xl/gm/modules/attention.py
examples/stable_diffusion_xl/gm/modules/diffusionmodules/model.py
examples/stable_diffusion_xl/gm/modules/diffusionmodules/openaimodel.py
examples/stable_diffusion_xl/scripts/run_train_dynamic.sh
examples/stable_diffusion_xl/train.py

Support Dynamic Shape

---

examples/stable_diffusion_xl/gm/helpers.py
examples/stable_diffusion_xl/train_dreambooth.py

enable graph kernel for ascend and fix dreambooth bug
@xxx

enable graph kernel for ascend

---

examples/fit/configs/inference/fit-xl-2-256x256.yaml
examples/fit/pipelines/infer_pipeline.py
examples/fit/pipelines/train_pipeline.py
examples/fit/sample.py
examples/fit/train.py
mindone/models/fit.py
mindone/models/latte.py
mindone/models/modules/pos_embed.py

- FiT FlashAttention Support
- clean redundant code in fit train pipeline
- fix the inference bug when the sample image size (when H != W) is larger than the maximum size in training
- `get_1d_sincos_temp_embed` renamed as `get_1d_sincos_pos_embed` for better consistency
@xxx

FiT FA support and other updates

---

mindone/models/dit.py

Fix the bug that DiT `Attention` cannot handle mask which is not None. Using `ops.select` instead of `masked_fill` to fill mask with `-inf` value.

[BUG fix] DiT mask error

---

examples/opensora_cai/opensora/models/layers/blocks.py
examples/opensora_cai/train_t2v.py
mindone/models/modules/flash_attention.py
mindone/trainers/train_step.py

opensora speed up trick

---

examples/diffusers/text_to_image/train_text_to_image_sdxl.py
mindone/diffusers/training_utils.py
mindone/transformers/activations_ms.py

Fixed bugs in mindone.diffusers sdxl training to support:
- distributed training
- timesteps bias sampling
- save/resume checkpoint
- snr gamma loss weighting
- RandomCrop data preprocessing
-  datasets sharding in data parallel
-  make learning rate schedulers take effect
@xxx

Fix(diffusers/sdxl): mindone.diffusers SDXL training fixes

---

examples/diffusers/text_to_image/README.md
examples/diffusers/text_to_image/README_sdxl.md
examples/diffusers/text_to_image/train_text_to_image.py

feat(diffusers/sd): add training of stable diffusion

---

examples/diffusers/unconditional_image_generation/README.md
examples/diffusers/unconditional_image_generation/train_unconditional.py
mindone/diffusers/__init__.py
mindone/diffusers/models/__init__.py
mindone/diffusers/models/unets/__init__.py
mindone/diffusers/models/unets/unet_2d.py
mindone/diffusers/models/unets/unet_2d_blocks.py
mindone/diffusers/pipelines/ddim/pipeline_ddim.py
mindone/diffusers/pipelines/ddpm/pipeline_ddpm.py

feat(diffusers): add training of unconditional generation

---

examples/diffusers/text_to_image/train_text_to_image.py
examples/diffusers/text_to_image/train_text_to_image_sdxl.py

fix(diffusers): typo in `freeze_params`, `requires_grad` instead of `require_grad`

---

examples/opensora_hpcai/README.md
examples/opensora_hpcai/docs/quick_start.md
examples/opensora_hpcai/tools/convert_t5.py
examples/opensora_hpcai/tools/convert_vae.py

`parser.add_argument("--src", ...)` but then `torch_to_ms_weight(args.source, target_fp)`

[OpenSora] fix T5 converter

---

examples/stable_diffusion_xl/demo/sampling_without_streamlit.py
examples/stable_diffusion_xl/gm/models/diffusion.py
examples/stable_diffusion_xl/gm/modules/diffusionmodules/sampler.py
examples/stable_diffusion_xl/gm/util/long_prompt.py

sdxl: add init noise scheduler for EulerA sampler

---

.github/workflows/ci.yml
mindone/diffusers/README.md
mindone/diffusers/__init__.py
mindone/diffusers/schedulers/__init__.py
mindone/diffusers/schedulers/scheduling_ddim.py
mindone/diffusers/schedulers/scheduling_ddpm.py
mindone/diffusers/schedulers/scheduling_deis_multistep.py
mindone/diffusers/schedulers/scheduling_dpmsolver_multistep.py
mindone/diffusers/schedulers/scheduling_dpmsolver_singlestep.py
mindone/diffusers/schedulers/scheduling_euler_ancestral_discrete.py
mindone/diffusers/schedulers/scheduling_heun_discrete.py
mindone/diffusers/schedulers/scheduling_k_dpm_2_ancestral_discrete.py
mindone/diffusers/schedulers/scheduling_k_dpm_2_discrete.py
mindone/diffusers/schedulers/scheduling_lms_discrete.py
mindone/diffusers/schedulers/scheduling_pndm.py
mindone/diffusers/schedulers/scheduling_unipc_multistep.py
tests/diffusers/test_schedulers.py
tests/diffusers/test_schedulers_graph.py

feat(diffusers/schedulers): add KarrasDiffusionSchedulers

---

examples/stable_diffusion_xl/configs/training/sd_xl_base_finetune_multi_aspect_dreambooth.yaml
examples/stable_diffusion_xl/configs/training/sd_xl_base_finetune_multi_aspect_lora.yaml
examples/stable_diffusion_xl/gm/modules/diffusionmodules/model.py
examples/stable_diffusion_xl/train.py
examples/stable_diffusion_xl/train_dreambooth.py

Support Dynamic Shape Based on Lora, Dreambooth, Flash Attention

---

examples/diffusers/text_to_image/train_text_to_image.py
examples/diffusers/text_to_image/train_text_to_image_lora.py
examples/diffusers/text_to_image/train_text_to_image_lora_sdxl.py
examples/diffusers/text_to_image/train_text_to_image_sdxl.py
examples/diffusers/unconditional_image_generation/train_unconditional.py
mindone/diffusers/models/attention_processor.py
mindone/diffusers/models/autoencoders/autoencoder_kl.py
mindone/diffusers/models/modeling_utils.py
mindone/diffusers/models/unets/unet_2d_condition.py
mindone/diffusers/pipelines/pipeline_utils.py
mindone/transformers/models/clip/modeling_ms_clip.py

feat(diffusers/xformers): support memory efficient attention

---

mindone/transformers/README.md
mindone/transformers/__init__.py
mindone/transformers/modeling_ms_utils.py
mindone/transformers/models/__init__.py
mindone/transformers/models/t5/__init__.py
mindone/transformers/models/t5/modeling_t5.py

This pr is proposed to add T5ForConditionalGeneration Model. Google/flan-t5-large has been supported in graph mode and pynative mode.
Additionally, the instruction for using T5 model series has been added. 
@xxx

Flan-t5-large: Graph Mode and Pynative Mode

---

examples/opensora_hpcai/scripts/inference_i2v.py

OpenSora v1.1: align inference_i2v.py with #500

---

examples/opensora_hpcai/README.md
examples/opensora_hpcai/opensora/datasets/video_dataset_refactored.py

Remove required `length` column dependency in CSV files.

OpenSora v1.1: remove `length` dependency

---

mindone/diffusers/image_processor.py
mindone/diffusers/models/__init__.py
mindone/diffusers/models/adapter.py
mindone/diffusers/models/attention.py
mindone/diffusers/models/attention_processor.py
mindone/diffusers/models/autoencoders/vae.py
mindone/diffusers/models/controlnet.py
mindone/diffusers/models/downsampling.py
mindone/diffusers/models/embeddings.py
mindone/diffusers/models/normalization.py
mindone/diffusers/models/resnet.py
mindone/diffusers/models/transformers/transformer_2d.py
mindone/diffusers/models/unets/unet_2d_condition.py
mindone/diffusers/models/upsampling.py
tests/diffusers/models/test_layers.py
tests/diffusers/models/test_layers_cases.py

implements of layers in `mindone.diffusers.models`
@xxx

feat(diffusers/models): add layers like norm, upsample, downsample and etc.

---

examples/opensora_hpcai/opensora/datasets/t2v_dataset.py

Improve performance of data preprocess.
Import normalization performance by vectorization.
Before:
```
normalize cost:  0.5943191051483154
normalize cost:  0.6660106182098389
normalize cost:  0.6163914203643799
normalize cost:  0.6558637619018555
normalize cost:  0.8292555809020996
normalize cost:  0.8465554714202881
normalize cost:  0.8598706722259521
normalize cost:  0.8413074016571045
normalize cost:  0.8623526096343994
normalize cost:  0.8590891361236572
normalize cost:  0.8666942119598389
normalize cost:  0.8659505844116211
normalize cost:  0.843127965927124
normalize cost:  0.898564338684082
normalize cost:  0.8245420455932617
normalize cost:  0.8166720867156982
```
After:
```
normalize cost:  0.2826392650604248
normalize cost:  0.2461528778076172
normalize cost: …
```

Improve normalization performance by vectorization

---

examples/opensora_hpcai/opensora/models/layers/blocks.py
examples/opensora_hpcai/opensora/models/stdit/stdit.py
examples/opensora_hpcai/opensora/models/stdit/stdit2.py

STDiT support linear patch embed with pretrained ckpt

---

examples/opensora_hpcai/README.md
examples/opensora_hpcai/scripts/run/run_infer_t2v_parallel.sh
examples/opensora_hpcai/scripts/run/run_infer_t5_parallel.sh
examples/opensora_hpcai/scripts/run/run_infer_vae_parallel.sh

- fix inference scripts to adapt for running on cloud
- fix readme

Opensora-hpcai: fixes on scripts

---

examples/stable_diffusion_v2/README.md
examples/stable_diffusion_v2/docs/en/faq.md

add FAQ readme for sdv2

---

mindone/diffusers/schedulers/scheduling_ddim.py
mindone/diffusers/schedulers/scheduling_ddim_inverse.py
mindone/diffusers/schedulers/scheduling_ddim_parallel.py
mindone/diffusers/schedulers/scheduling_ddpm.py
mindone/diffusers/schedulers/scheduling_ddpm_parallel.py
mindone/diffusers/schedulers/scheduling_deis_multistep.py
mindone/diffusers/schedulers/scheduling_dpmsolver_multistep.py
mindone/diffusers/schedulers/scheduling_dpmsolver_multistep_inverse.py
mindone/diffusers/schedulers/scheduling_dpmsolver_singlestep.py
mindone/diffusers/schedulers/scheduling_edm_dpmsolver_multistep.py
mindone/diffusers/schedulers/scheduling_euler_ancestral_discrete.py
mindone/diffusers/schedulers/scheduling_euler_discrete.py
mindone/diffusers/schedulers/scheduling_heun_discrete.py
mindone/diffusers/schedulers/scheduling_k_dpm_2_ancestral_discrete.py
mindone/diffusers/schedulers/scheduling_k_dpm_2_discrete.py
mindone/diffusers/schedulers/scheduling_lcm.py
mindone/diffusers/schedulers/scheduling_lms_discrete.py
mindone/diffusers/schedulers/scheduling_sasolver.py
mindone/diffusers/schedulers/scheduling_tcd.py
mindone/diffusers/schedulers/scheduling_unipc_multistep.py

fix(diffusers/schedulers): fix some bugs in schedulers

---

examples/diffusers/text_to_image/train_text_to_image.py
examples/diffusers/text_to_image/train_text_to_image_lora.py
examples/diffusers/text_to_image/train_text_to_image_lora_sdxl.py
examples/diffusers/text_to_image/train_text_to_image_sdxl.py
examples/diffusers/unconditional_image_generation/train_unconditional.py
mindone/diffusers/training_utils.py

refactor(diffusers/training): TrainStep supports gradients accum/clip/scale

---

README.md
mindone/diffusers/__init__.py
mindone/diffusers/image_processor.py
mindone/diffusers/models/__init__.py
mindone/diffusers/models/activations.py
mindone/diffusers/models/attention.py
mindone/diffusers/models/attention_processor.py
mindone/diffusers/models/autoencoders/autoencoder_kl.py
mindone/diffusers/models/embeddings.py
mindone/diffusers/models/normalization.py
mindone/diffusers/models/transformers/__init__.py
mindone/diffusers/models/transformers/transformer_sd3.py
mindone/diffusers/pipelines/__init__.py
mindone/diffusers/pipelines/pipeline_loading_utils.py
mindone/diffusers/pipelines/stable_diffusion_3/__init__.py
mindone/diffusers/pipelines/stable_diffusion_3/pipeline_output.py
mindone/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py
mindone/diffusers/schedulers/__init__.py
mindone/diffusers/schedulers/scheduling_flow_match_euler_discrete.py

feat(diffusers/sd3): add stable diffusion 3 pipeline

---

mindone/diffusers/models/normalization.py

1. Add `name` for parameters defined by `mindspore.Parameter()` to make sure `param.set_dtype()` works just right, so we won't have to cast it manually 
2. Change the parameter order of `LayerNorm.__init__()` to maintain consistency with torch.
@geniuspatrick @CaitinZhao

refactor(diffusers/layers): layer&group norm

---

examples/stable_diffusion_xl/docs/faq_cn.md
examples/stable_diffusion_xl/docs/inference.md

update speed of sdxl samplers, update FA usage on Ascend 910

sdxl readme: update support list, update FA usage

---

.github/workflows/ci.yml

fix(ci): fix ci bugs

---

mindone/diffusers/README.md
mindone/diffusers/loaders/__init__.py
mindone/diffusers/loaders/autoencoder.py
mindone/diffusers/loaders/controlnet.py
mindone/diffusers/loaders/ip_adapter.py
mindone/diffusers/loaders/single_file.py
mindone/diffusers/loaders/single_file_utils.py
mindone/diffusers/loaders/textual_inversion.py
mindone/diffusers/loaders/unet.py
mindone/diffusers/models/autoencoders/autoencoder_kl.py
mindone/diffusers/models/unets/unet_2d_condition.py
mindone/diffusers/pipelines/pipeline_utils.py
mindone/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
mindone/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
mindone/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py
mindone/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py
mindone/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py
mindone/transformers/modeling_utils.py

add loaders: autoencoders, controlnet, single_file, ip_adapter, textual_inversion.
We provides an easy-to-use LoaderMixin API to load adapter weights
**Textual inversion** is very similar to DreamBooth and it can also personalize a diffusion model to generate certain concepts (styles, objects) from just a few images. Now you can load the textual inversion embeddings with the `load_textual_inversion()` method and generate some images. Let’s load [sd-concepts-library/gta5-artwork](https://huggingface.co/sd-concepts-library/gta5-artwork) embeddings and you’ll need to include the special word <gta5-artwork> in your prompt to trigger it:
```python
from mindone.diffusers import StableDiffusionPipeline
pipeline = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5") …
```

feat(diffusers/loaders): add loaders for controlnet, ti and etc.

---

examples/opensora_pku/README.md

Update pku opensora readme

---

examples/opensora_hpcai/README.md
examples/opensora_hpcai/configs/opensora-v1-1/train/stdit2_512x512x64.yaml
examples/opensora_hpcai/configs/opensora-v1-1/train/stdit2_576x1024x24.yaml
examples/opensora_hpcai/docs/quick_start.md
examples/opensora_hpcai/scripts/args_train.py
examples/opensora_hpcai/scripts/infer_t5.py
examples/opensora_hpcai/scripts/infer_vae.py
examples/opensora_hpcai/scripts/inference.py
examples/opensora_hpcai/scripts/run/run_infer_os_v1.1_t2v_parallel.sh
examples/opensora_hpcai/scripts/run/run_train_256x256x16_parallel.sh
examples/opensora_hpcai/scripts/run/run_train_512x512x64_parallel_bf16.sh
examples/opensora_hpcai/scripts/run/run_train_512x512x64_parallel_dvm_cached.sh
examples/opensora_hpcai/scripts/run/run_train_512x512x64_parallel_ge.sh
examples/opensora_hpcai/scripts/run/run_train_512x512x64_parallel_ge_fastest.sh
examples/opensora_hpcai/scripts/run/run_train_os_v1.1_576p.sh
examples/opensora_hpcai/scripts/run/run_train_os_v1.1_parallel.sh
examples/opensora_hpcai/scripts/train.py

update opensora-hpcai jit_level

---

examples/opensora_hpcai/opensora/datasets/t2v_dataset.py
examples/opensora_hpcai/opensora/datasets/video_dataset.py
examples/opensora_hpcai/opensora/datasets/video_dataset_refactored.py
examples/opensora_hpcai/scripts/args_train.py
examples/opensora_hpcai/scripts/infer_vae.py
examples/opensora_hpcai/scripts/train.py

Add non-existing files filtering.

OpenSora: add data filtering

---

examples/stable_diffusion_v2/common.py
examples/stable_diffusion_v2/depth_to_image.py
examples/stable_diffusion_v2/inpaint.py
examples/stable_diffusion_v2/text_to_image.py
examples/stable_diffusion_v2/train_cldm.py
examples/stable_diffusion_v2/train_dreambooth.py
examples/stable_diffusion_v2/train_text_to_image.py
examples/stable_diffusion_v2/train_textual_inversion.py
examples/stable_diffusion_v2/train_unclip_image_variation.py
examples/stable_diffusion_v2/unclip_image_variation.py
examples/stable_diffusion_xl/gm/helpers.py
examples/stable_diffusion_xl/gm/modules/attention.py
examples/stable_diffusion_xl/gm/modules/diffusionmodules/sampler.py
examples/stable_diffusion_xl/gm/modules/embedders/clip/modeling_clip.py
examples/stable_diffusion_xl/gm/modules/lora/layers.py
examples/stable_diffusion_xl/gm/modules/transformers/transformers.py
examples/stable_diffusion_xl/gm/util/util.py
examples/stable_diffusion_xl/train.py
examples/stable_diffusion_xl/train_controlnet.py
examples/stable_diffusion_xl/train_dreambooth.py
examples/stable_diffusion_xl/train_textual_inversion.py

update jit_level for  sdv2

---

mindone/diffusers/utils/__init__.py
mindone/diffusers/utils/export_utils.py
mindone/diffusers/utils/import_utils.py

Add some utils in `mindone.diffusers`, including:
`BACKENDS_MAPPING` containing `bs`, `opencv`, `ftfy`  to check if it is available for importing or not
export utils such as `export_to_gif`, `export_to_obj` and etc to export outputs of models to specific file format
@geniuspatrick @CaitinZhao

feat(diffusers/utils): import&export utils

---

examples/stable_diffusion_v2/common.py

fix jit bug

---

examples/stable_diffusion_xl/configs/training/sd_xl_base_finetune_multi_aspect_dreambooth.yaml
examples/stable_diffusion_xl/configs/training/sd_xl_base_finetune_multi_aspect_lora.yaml
examples/stable_diffusion_xl/gm/modules/attention.py
examples/stable_diffusion_xl/gm/modules/diffusionmodules/model.py
examples/stable_diffusion_xl/gm/modules/diffusionmodules/openaimodel.py
examples/stable_diffusion_xl/scripts/run_distribute_vanilla_ft_dynamic_shape.sh
examples/stable_diffusion_xl/scripts/run_infer_dynamic_shape.sh
examples/stable_diffusion_xl/scripts/run_train_dynamic_shape.sh
examples/stable_diffusion_xl/train.py
examples/stable_diffusion_xl/train_dreambooth.py

support sdxl dynamic shape vanilla, lora, dreambooth finetune

---

examples/stable_diffusion_xl/train_dreambooth.py

fix sdxl dreambooth bug

---

examples/diffusers/textual_inversion/README.md
examples/diffusers/textual_inversion/README_sdxl.md
examples/diffusers/textual_inversion/textual_inversion.py
examples/diffusers/textual_inversion/textual_inversion_sdxl.py
mindone/transformers/modeling_utils.py

feat(diffusers/training): add training of textural inversion

---

examples/diffusers/dreambooth/README.md
examples/diffusers/dreambooth/README_sdxl.md
examples/diffusers/dreambooth/train_dreambooth.py
examples/diffusers/dreambooth/train_dreambooth_lora.py
examples/diffusers/dreambooth/train_dreambooth_lora_sdxl.py

feat(diffusers/training): add training of dreambooth

---

examples/diffusers/controlnet/README.md
examples/diffusers/controlnet/README_sdxl.md
examples/diffusers/controlnet/train_controlnet.py
examples/diffusers/controlnet/train_controlnet_sdxl.py
mindone/diffusers/models/controlnet.py

feat(diffusers/training): add training of controlnet

---

examples/stable_diffusion_v2/benchmark.md

update sdv2 benchmark for ms2.3

---

examples/opensora_pku/README.md
examples/opensora_pku/opensora/dataset/t2v_dataset.py
examples/opensora_pku/opensora/train/train_t2v.py
examples/opensora_pku/scripts/text_condition/train_videoae_513x512x512_sp.sh

None
1. add stage3 513*512*512 training
2. update pku readme
@xxx

opensora-pku: add stage3 training

---

examples/opensora_hpcai/opensora/pipelines/infer_pipeline.py
examples/opensora_hpcai/opensora/pipelines/train_pipeline.py
examples/stable_diffusion_xl/offline_inference/libs/infer_engine/export_modules.py
examples/stable_diffusion_xl/offline_inference/libs/sd_models.py

style: make the `black` happy ;-)

---

examples/opensora_pku/README.md
examples/opensora_pku/scripts/embedding_cache/extract_all.sh
examples/opensora_pku/scripts/embedding_cache/extract_multi.sh
examples/opensora_pku/scripts/train_data/image_data.txt
examples/opensora_pku/scripts/train_data/video_data.txt
examples/opensora_pku/scripts/train_data/video_data_513.txt

OpenSora-PKU v1.1.0: Improve readme

---

mindone/diffusers/__init__.py
mindone/diffusers/models/unets/unet_1d.py
mindone/diffusers/models/unets/unet_1d_blocks.py

fix(diffusers/unet_1d_blocks): fix some bugs in unet_1d_blocks

---

examples/stable_diffusion_xl/demo/sampling_without_streamlit.py
examples/stable_diffusion_xl/gm/data/dataset.py

1. unlimit the shape number restriction by modifying dataset part
2. abandon interface about setting random seed for multi_aspect
@xxx

fix sdxl dynamic shape bug

---

.github/workflows/ci.yml

restrict the MindSpore version to 2.2.14 in the workflow
@xxx

chore(workflow): restrict the MindSpore version to 2.2.14 in the workflow temporarily.

---

examples/opensora_pku/opensora/models/diffusion/latte/net_with_loss.py

opensora pku: fix timestep sample with seq parallel

---

mindone/transformers/__init__.py
mindone/transformers/modeling_outputs.py
mindone/transformers/models/mt5/__init__.py
mindone/transformers/models/mt5/modeling_mt5.py

support mt5 pipeline inference.
tested on ms2.3 release version + 910*
update how to use mt5 in readme
@xxx

feat: support mt5 model

---

examples/diffusers/dreambooth/README_sd3.md
examples/diffusers/dreambooth/requirements_sd3.txt
examples/diffusers/dreambooth/train_dreambooth_lora_sd3.py
examples/diffusers/dreambooth/train_dreambooth_sd3.py
mindone/diffusers/loaders/__init__.py
mindone/diffusers/loaders/lora.py
mindone/diffusers/models/activations.py
mindone/diffusers/models/attention_processor.py
mindone/diffusers/models/autoencoders/autoencoder_kl_temporal_decoder.py
mindone/diffusers/models/autoencoders/vae.py
mindone/diffusers/models/embeddings.py
mindone/diffusers/models/normalization.py
mindone/diffusers/models/resnet.py
mindone/diffusers/models/transformers/t5_film_transformer.py
mindone/diffusers/models/transformers/transformer_sd3.py
mindone/diffusers/models/unets/unet_2d_blocks.py
mindone/diffusers/models/unets/unet_i2vgen_xl.py
mindone/diffusers/models/unets/unet_kandinsky3.py
mindone/diffusers/models/unets/unet_motion_model.py
mindone/diffusers/models/unets/unet_spatio_temporal_condition.py
mindone/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py

Adds SD3 training scripts:
- **vanilla-finetune or DreamBooth**: examples/diffusers/dreambooth/train_dreambooth_sd3.py 
- **LoRA or DreamBooth-LoRA**: examples/diffusers/dreambooth/train_dreambooth_lora_sd3.py
and relative modifications on models/pipelines/utils
@xxx

feat(diffusers/training): add training of sd3

---

README.md
examples/README.md
examples/diffusers/README.md
examples/diffusers/text_to_image/train_text_to_image_sdxl.py
mindone/diffusers/models/layers_compat.py
mindone/diffusers/models/normalization.py
mindone/diffusers/models/resnet.py
mindone/diffusers/models/unets/unet_1d_blocks.py
mindone/diffusers/models/upsampling.py
mindone/diffusers/training_utils.py

Consolidating operators that were unsupported or unsupported in previous versions of the MindSpore framework into a unified file, contains:
- multinomial: **unsupported** in mindspore2.2 and Ascend 910*; **supported** in mindspore2.3
- conv_transpose2d: **unsupported** in mindspore2.2; **supported** in mindspore2.3
- group_norm: **unfused impl** in mindspore2.2; **fused impl** in mindspore2.3
- pad: **unsupported** in some scenarios with mindspore2.2; **supported** in mindspore2.3
- conv_transpose1d: **unsupported** in mindspore2.2&2.3
members/contributors who may be …

refactor: refactored interfaces for compatibility

---

examples/diffusers/dreambooth/README_sd3.md

Correct context in README about SD3
@xxx

doc(README): correct context

---

examples/opensora_hpcai/opensora/models/layers/operation_selector.py
examples/opensora_hpcai/opensora/models/layers/rotary_embedding.py

fix mint.chunk

---

examples/stable_diffusion_v2/tools/model_conversion/convert_weights.py

fix sd model convert bug

---

mindone/transformers/modeling_utils.py

fix(transformers): fix some bugs about prefix in load_param

---

mindone/transformers/__init__.py
mindone/transformers/modeling_outputs.py
mindone/transformers/models/__init__.py
mindone/transformers/models/bert/__init__.py
mindone/transformers/models/bert/modeling_bert.py

feat(transformers/models): add Bert

---

mindone/transformers/modeling_utils.py

fix(transformers/models):fix some bugs

---

mindone/diffusers/models/attention_processor.py
mindone/diffusers/models/transformers/transformer_sd3.py

This PR supports fused qkv for SD3. To enable it, add `pipe.transformer.fuse_qkv_projections()` to origin SD3 pipeline calling example:
```py
import mindspore
from mindone.diffusers import StableDiffusion3Pipeline
pipe = StableDiffusion3Pipeline.from_pretrained(
"stabilityai/stable-diffusion-3-medium-diffusers",
mindspore_dtype=mindspore.float16,
)
pipe.transformer.fuse_qkv_projections()
prompt = "A cat holding a sign that says hello world"
image = pipe(prompt)[0][0]
image.save("sd3.png")
```
@xxx

feat(diffusers): support fused qkv for SD3

---

examples/stable_diffusion_v2/README.md
examples/stable_diffusion_v2/common.py
examples/stable_diffusion_v2/inpaint.py
examples/stable_diffusion_v2/scripts/run_infer_distributed.sh
examples/stable_diffusion_v2/scripts/run_train_distributed.sh
examples/stable_diffusion_v2/text_to_image.py
examples/stable_diffusion_v2/train_autoencoder.py
examples/stable_diffusion_v2/train_cldm.py
examples/stable_diffusion_v2/train_dreambooth.py
examples/stable_diffusion_v2/train_text_to_image.py
examples/stable_diffusion_v2/train_unclip_image_variation.py
examples/stable_diffusion_v2/unclip_image_variation.py

update sdv2 readme and fix distribute bug

---

examples/opensora_hpcai/tools/caption/llava_next/README.md
examples/opensora_hpcai/tools/caption/llava_next/llava/model/activation.py
examples/opensora_hpcai/tools/caption/llava_next/llava/model/clip/__init__.py
examples/opensora_hpcai/tools/caption/llava_next/llava/model/clip/layer.py
examples/opensora_hpcai/tools/caption/llava_next/llava/model/clip/network.py
examples/opensora_hpcai/tools/caption/llava_next/llava/model/common_layer.py
examples/opensora_hpcai/tools/caption/llava_next/llava/model/llava_next/__init__.py
examples/opensora_hpcai/tools/caption/llava_next/llava/model/llava_next/network.py
examples/opensora_hpcai/tools/caption/llava_next/llava/model/llava_next/utils.py
examples/opensora_hpcai/tools/caption/llava_next/llava/model/mistral/__init__.py
examples/opensora_hpcai/tools/caption/llava_next/llava/model/mistral/layer.py
examples/opensora_hpcai/tools/caption/llava_next/llava/model/mistral/network.py
examples/opensora_hpcai/tools/caption/llava_next/llava/model/padding.py
examples/opensora_hpcai/tools/caption/llava_next/llava/pipeline/__init__.py
examples/opensora_hpcai/tools/caption/llava_next/llava/pipeline/helpers/__init__.py
examples/opensora_hpcai/tools/caption/llava_next/llava/pipeline/helpers/stopping_criteria.py
examples/opensora_hpcai/tools/caption/llava_next/llava/pipeline/text_generation.py
examples/opensora_hpcai/tools/caption/llava_next/predict.py
examples/opensora_hpcai/tools/caption/llava_next/tools/convert_llava.py
examples/opensora_hpcai/tools/caption/llava_next/tools/fileio/__init__.py
examples/opensora_hpcai/tools/caption/llava_next/tools/fileio/safetensors.py

[OpenSora-HPCAI] Llava-Next Captioner

---

examples/opensora_hpcai/configs/opensora-v1-2/train/train_stage1_ms.yaml

update opensora-hpcai-1.2 stage1 for bucket balance

---

examples/opensora_hpcai/README.md
examples/opensora_hpcai/opensora/acceleration/communications.py
examples/opensora_hpcai/opensora/acceleration/parallel_states.py
examples/opensora_hpcai/opensora/models/layers/blocks.py
examples/opensora_hpcai/opensora/models/stdit/stdit3.py
examples/opensora_hpcai/opensora/models/vae/autoencoder_kl.py
examples/opensora_hpcai/opensora/models/vae/vae.py
examples/opensora_hpcai/opensora/models/vae/vae_temporal.py
examples/opensora_hpcai/opensora/schedulers/rectified_flow.py
examples/opensora_hpcai/scripts/args_train.py
examples/opensora_hpcai/scripts/inference.py
examples/opensora_hpcai/scripts/run/run_infer_sequence_parallel.sh
examples/opensora_hpcai/scripts/run/run_train_os1.2_stage2_sp.sh
examples/opensora_hpcai/scripts/train.py
examples/opensora_hpcai/tests/run_test_stdit3_sequence_parallelism.sh
examples/opensora_hpcai/tests/run_test_vae_1_2_parallelism.sh
examples/opensora_hpcai/tests/test_stdit3_sequence_parallelism.py
examples/opensora_hpcai/tests/test_vae_1_2_parallelism.py

support training and inference with sequence parallel for v1.2
@xxx

Os v1.2 / VAE support SP

---

.github/CODEOWNERS

chore: G. Patrick is deprecated in CODEOWNERS

---

examples/stable_diffusion_xl/train_dreambooth.py

bugfix: fix SDXL dreambooth memory bug in jit level O0

---

examples/t2i_adapter/README.md

to update mindspore/ascend cann version info to t2i adapter model readme
@xxx

update mindspore version to t2i adapter readme

---

examples/opensora_pku/opensora/eval/script/cal_lpips.sh
examples/opensora_pku/opensora/eval/script/cal_psnr.sh
examples/opensora_pku/opensora/utils/ms_utils.py

Some files were missing from my last PR #698 to synchronize v0.2.0 with the master branch on opensora-pku v1.1.0. Sorry for the trouble.

[OpenSora-PKU]: add missing files to v0.2.0

---

mindone/diffusers/models/attention_processor.py

Make mindone.diffusers version 0.29 backward compatible with mindspore versions prior to 2.3.0. related to #693 
@xxx

refactor(diffusers): backward compatibility for MindSpore before v2.3.0

---

mindone/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py
mindone/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py
mindone/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py

fix ip_adapter loading bug in sdxl
@xxx

fix(diffusers/pipelines): fix ip_adapter loading bug in sdxl

---

mindone/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_instruct_pix2pix.py

update stable diffusion instruct_pix2pix pipeline to diffusers v0.29.2
@xxx

feat(diffusers/pipelines): update stable diffusion instruct_pix2pix pipeline to diffusers v0.29.2

---

examples/kohya_sd_scripts/library/model_util.py
examples/kohya_sd_scripts/library/sdxl_model_util.py
examples/kohya_sd_scripts/library/sdxl_original_unet.py

feat: add files for Kohya's sdxl-lora library

---

examples/diffusers/controlnet/README_sdxl.md
examples/diffusers/dreambooth/README_sdxl.md

doc(examples/diffusers): correct documents

---

.github/workflows/ci.yml

upgrade diffusers version

---

examples/pixart_sigma/README.md

[DOC] update PixArt README

---

examples/opensora_pku/README.md

fix readme format issue

---

examples/dit/README_CN.md
examples/dit/args_train.py
examples/dit/sample.py
examples/dit/train.py
examples/latte/README.md
examples/latte/README_CN.md
examples/latte/args_train.py
examples/latte/requirements.txt
examples/latte/sample.py
examples/latte/train.py

Adds #615
dit and latte model performance update with ms 2.3
@xxx

update latte/dit to ms2.3

---

examples/stable_diffusion_xl/docs/textual_inversion_finetune.md
examples/stable_diffusion_xl/tools/model_conversion/README.md

Commit d008a71d670a79ccb18a1da9d9b1434ee3858bce moved bunch of stable diffusion files. This PR adjusts sources to changes.

fix: update stable diffusion references

---

examples/animatediff/README.md
examples/animatediff/ad/modules/diffusionmodules/openaimodel.py
examples/animatediff/ad/modules/diffusionmodules/sparse_controlnet.py
examples/animatediff/ad/modules/diffusionmodules/unet3d.py
examples/animatediff/ad/utils/cond_data.py
examples/animatediff/configs/stable_diffusion/v1-train-mmv2-cache.yaml
examples/animatediff/configs/training/mmv2_train_cache.yaml
examples/animatediff/scripts/convert_weights.sh
examples/animatediff/train.py

update benchmark, ms version of example/animatediff docs and readme. and some bugfix
@xxx

update benchmark, ms version of example/animatediff readme, and some bugfix

---

examples/dynamicrafter/README.md
examples/dynamicrafter/lvdm/models/ddpm3d.py

Tested dynamicrafter on MS 2.3.1 and update doc.
@xxx

Update dynamicrafter doc for ms2.3.1

---

examples/opensora_pku/README.md

1. Correct the downlink of cann toolkit.
2. Correct format error in readme.

Open-Sora-Plan-v1.2.0: update readme

---

mindone/transformers/models/bert/modeling_bert.py

fix(transformers/bert): prevent the existence of 'none' in the return

---

examples/stable_diffusion_xl/configs/training/sd_xl_base_finetune_multi_aspect_dreambooth.yaml
examples/stable_diffusion_xl/configs/training/sd_xl_base_finetune_multi_aspect_lora.yaml
examples/stable_diffusion_xl/demo/sampling_without_streamlit.py
examples/stable_diffusion_xl/gm/data/dataset.py
examples/stable_diffusion_xl/gm/helpers.py
examples/stable_diffusion_xl/gm/modules/attention.py
examples/stable_diffusion_xl/gm/modules/diffusionmodules/model.py
examples/stable_diffusion_xl/gm/modules/diffusionmodules/openaimodel.py
examples/stable_diffusion_xl/gm/modules/diffusionmodules/sampler.py
examples/stable_diffusion_xl/gm/modules/embedders/clip/modeling_clip.py
examples/stable_diffusion_xl/gm/modules/lora/layers.py
examples/stable_diffusion_xl/gm/modules/transformers/transformers.py
examples/stable_diffusion_xl/gm/util/util.py
examples/stable_diffusion_xl/scripts/run_distribute_vanilla_ft_dynamic_shape.sh
examples/stable_diffusion_xl/scripts/run_infer_dynamic_shape.sh
examples/stable_diffusion_xl/scripts/run_train_dynamic_shape.sh
examples/stable_diffusion_xl/train.py
examples/stable_diffusion_xl/train_controlnet.py
examples/stable_diffusion_xl/train_dreambooth.py
examples/stable_diffusion_xl/train_textual_inversion.py

feat(examples/sdxl): upgrade sdxl to ms2.3(jit_level/dynamic shape)

---

examples/opensora_pku/README.md
examples/opensora_pku/examples/rec_image.py
examples/opensora_pku/examples/rec_video.py
examples/opensora_pku/examples/rec_video_folder.py
examples/opensora_pku/opensora/eval/eval_common_metrics.py
examples/opensora_pku/opensora/models/causalvideovae/model/losses/discriminator.py
examples/opensora_pku/opensora/models/causalvideovae/model/modules/conv.py
examples/opensora_pku/opensora/train/train_causalvae.py
examples/opensora_pku/scripts/causalvae/train_with_gan_loss.sh
examples/opensora_pku/scripts/causalvae/train_with_gan_loss_multi_device.sh

1. add vae 1.2  training.
2. fix loss scale bug.
@xxx

update pku vae 1.2 training

---

examples/hunyuan_dit/IndexKits/bin/idk
examples/opensora_pku/opensora/train/train_causalvae.py

fix bug for pku vae traning

---

examples/opensora_pku/README.md

To align with the [Wiki doc](https://github.com/mindspore-lab/mindone/wiki/%E6%A8%A1%E5%9E%8B%E7%89%88%E6%9C%AC%E4%B9%A6%E5%86%99%E6%A0%B7%E4%BE%8B), I revised the readme file of Open-Sora-Plan-v1.2.0.

[Open-Sora-Plan-v1.2.0] Update readme

---

examples/opensora_pku/README.md
examples/opensora_pku/examples/rec_video_folder.py
examples/opensora_pku/opensora/models/causalvideovae/model/causal_vae/modeling_causalvae.py
examples/opensora_pku/opensora/models/causalvideovae/model/losses/discriminator.py
examples/opensora_pku/opensora/models/causalvideovae/model/losses/net_with_loss.py
examples/opensora_pku/opensora/models/causalvideovae/model/modules/conv.py
examples/opensora_pku/opensora/train/train_causalvae.py
examples/opensora_pku/scripts/causalvae/eval.sh
examples/opensora_pku/scripts/causalvae/train_with_gan_loss_multi_device.sh
examples/opensora_pku/scripts/causalvae/train_without_gan_loss_multi_device.sh

cherry-pick pku-opensora update to v0.2.0

---

examples/opensora_hpcai/README.md
examples/opensora_hpcai/configs/opensora/train/stdit_512x512x64_ms.yaml

update hpcai-opensora 1.0 doc and config

---

README.md

tag for v0.2.0

---

.github/workflows/publish.yml

chore: change OIDC token permissions

---

examples/flux/README.md
examples/flux/__init__.py
examples/flux/__main__.py
examples/flux/cli.py
examples/flux/math.py
examples/flux/model.py
examples/flux/modules/autoencoder.py
examples/flux/modules/conditioner.py
examples/flux/modules/layers.py
examples/flux/requirement.txt
examples/flux/sampling.py
examples/flux/util.py

**Introduce Flux.1 for MindSpore**
@xxx

feat(flux): introduce Flux.1 for MindSpore

---

mindone/diffusers/models/attention_processor.py

fix(diffusers): fix bug of ip_adapter in graph mode

---

mindone/transformers/models/gemma/modeling_gemma.py

fix(transformers): fix some bugs in Gemma

---

docs/diffusers/_toctree.yml
docs/diffusers/api/models/controlnet_hunyuandit.md
docs/diffusers/api/models/latte_transformer3d.md
docs/diffusers/api/models/lumina_nextdit2d.md
docs/diffusers/api/pipelines/controlnet_hunyuandit.md
docs/diffusers/api/pipelines/kolors.md
docs/diffusers/api/pipelines/latte.md
docs/diffusers/api/pipelines/lumina.md
docs/diffusers/api/pipelines/pag.md
docs/diffusers/api/pipelines/stable_diffusion/stable_diffusion_3.md

fix some bugs in docs of diffusers
@xxx

fix(diffusers/docs): fix some bugs in docs of diffusers

---

examples/opensora_hpcai/README.md

- align with mindone v0.2.0 doc, update doc with ms2.3.1 
- update sequence parallel doc

opensora_hpcai: update doc with ms2.3.1

---

examples/opensora_hpcai/README.md
examples/opensora_hpcai/opensora/acceleration/parallel_states.py
examples/opensora_hpcai/opensora/models/stdit/__init__.py
examples/opensora_hpcai/opensora/models/stdit/stdit3_dsp.py
examples/opensora_hpcai/scripts/args_train.py
examples/opensora_hpcai/scripts/inference.py
examples/opensora_hpcai/scripts/run/run_infer_sequence_parallel_dsp.sh
examples/opensora_hpcai/scripts/run/run_train_os1.2_stage2_dsp.sh
examples/opensora_hpcai/scripts/train.py
examples/opensora_hpcai/tests/run_test_stdit3_sequence_parallelism_dsp.sh
examples/opensora_hpcai/tests/test_stdit3_sequence_parallelism_dsp.py

[OpenSora-hpcai] v1.2 add DSP support & optimize SP

---

mindone/diffusers/schedulers/scheduling_flow_match_euler_discrete.py
tests/diffusers_tests/modules/test_generic_modules.py
tests/modeling_test_utils.py
tests/transformers_tests/models/bert/test_modeling_bert.py
tests/transformers_tests/models/blip_2/test_modeling_blip_2.py
tests/transformers_tests/models/clip/test_modeling_clip.py
tests/transformers_tests/models/gemma/test_modeling_gemma.py
tests/transformers_tests/models/mt5/test_modeling_mt5.py
tests/transformers_tests/models/t5/test_modeling_t5.py

fix(diffusers&transformers/test): fix some bugs and disable some test cases
@xxx

fix(diffusers&transformers/test): fix some bugs and disable some test cases

---

examples/dit_infer_acceleration/tests/sd3_accuracy_test.py
examples/dit_infer_acceleration/tests/sd3_performance_test.py

Fix: fix dit infer sd3 testcase bug

---

examples/fit/README.md
examples/fit/args_train.py
examples/fit/configs/inference/fit-xl-2-256x256.yaml
examples/fit/configs/training/class_cond_train.yaml
examples/fit/data/imagenet_dataset.py
examples/fit/diffusion/gaussian_diffusion.py
examples/fit/preprocess.py
examples/fit/requirements.txt
examples/fit/sample.py
examples/fit/train.py
mindone/models/fit.py
mindone/utils/env.py

- FiT adapted to MS2.3.1 Jit=O0 Mode, loss is zero in Jit=O1, error in Jit=O2 mode 
- VAE using O1 dynamic shape inference instead of pynative to speed up the inference seed
- Transformer Turn on the Flash Attention default.
- Drop the env `DEVICE_ID` requirements when running with msrun
@xxx

FiT adapted to MS2.3.1

---

docs/diffusers/_toctree.yml
docs/diffusers/api/models/aura_flow_transformer2d.md
docs/diffusers/api/models/controlnet_sparsectrl.md
docs/diffusers/api/pipelines/animatediff.md
docs/diffusers/api/pipelines/aura_flow.md
mindone/diffusers/__init__.py
mindone/diffusers/models/__init__.py
mindone/diffusers/models/attention_processor.py
mindone/diffusers/models/controlnet_sparsectrl.py
mindone/diffusers/models/transformers/__init__.py
mindone/diffusers/models/transformers/auraflow_transformer_2d.py
mindone/diffusers/models/unets/unet_2d_condition.py
mindone/diffusers/pipelines/__init__.py
mindone/diffusers/pipelines/animatediff/__init__.py
mindone/diffusers/pipelines/animatediff/pipeline_animatediff_controlnet.py
mindone/diffusers/pipelines/animatediff/pipeline_animatediff_sparsectrl.py
mindone/diffusers/pipelines/aura_flow/__init__.py
mindone/diffusers/pipelines/aura_flow/pipeline_aura_flow.py
mindone/diffusers/pipelines/auto_pipeline.py
mindone/transformers/__init__.py
mindone/transformers/models/__init__.py
mindone/transformers/models/umt5/__init__.py
mindone/transformers/models/umt5/modeling_umt5.py
mindone/transformers/utils/__init__.py
tests/diffusers/pipelines/animatediff/test_animatediff_controlnet.py
tests/diffusers/pipelines/animatediff/test_animatediff_sparsectrl.py
tests/diffusers/pipelines/aura_flow/test_pipeline_aura_flow.py
tests/diffusers_tests/modules/modules_test_cases.py

add pipelines of animatediff and aura_flow
@xxx

feat(diffusers/pipelines):  add pipelines of animatediff and aura_flow

---

mindone/diffusers/schedulers/scheduling_flow_match_euler_discrete.py
tests/modeling_test_utils.py

fix(diffusers&transformers/test): fix test bugs

---

mindone/diffusers/_peft/peft_model.py
mindone/diffusers/_peft/tuners/lora/model.py
mindone/diffusers/_peft/utils/peft_types.py

fix(diffusers): some bugs about 'lora'

---

examples/svd/README.md
examples/svd/configs/svd_train.yaml
examples/svd/data/video_dataset.py
examples/svd/image_to_video.py
examples/svd/modules/helpers.py
examples/svd/modules/unet3d.py
examples/svd/train.py
examples/svd/utils.py
examples/t2i_adapter/README.md
examples/t2i_adapter/adapter_image2image_sd.py
examples/t2i_adapter/adapter_image2image_sdxl.py
examples/t2i_adapter/adapters/t2i_adapter.py
examples/t2i_adapter/data/dataset_with_cond.py
examples/t2i_adapter/t2i_utils.py
examples/t2i_adapter/train_t2i_adapter_sd.py
mindone/data/__init__.py

update svd and t2i_adapter to ms2.3.1

---

examples/diffusers/dreambooth/train_dreambooth.py
examples/diffusers/dreambooth/train_dreambooth_lora.py
mindone/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py

fix(diffusers): fix some bugs

---

examples/diffusers/controlnet/train_controlnet.py
examples/diffusers/controlnet/train_controlnet_sdxl.py
examples/diffusers/dreambooth/train_dreambooth.py
examples/diffusers/dreambooth/train_dreambooth_lora.py
examples/diffusers/dreambooth/train_dreambooth_lora_sd3.py
examples/diffusers/dreambooth/train_dreambooth_lora_sdxl.py
examples/diffusers/dreambooth/train_dreambooth_sd3.py
examples/diffusers/text_to_image/train_text_to_image.py
examples/diffusers/text_to_image/train_text_to_image_lora.py
examples/diffusers/text_to_image/train_text_to_image_lora_sdxl.py
examples/diffusers/text_to_image/train_text_to_image_sdxl.py
examples/diffusers/textual_inversion/textual_inversion.py
examples/diffusers/textual_inversion/textual_inversion_sdxl.py
examples/diffusers/unconditional_image_generation/train_unconditional.py

fix(diffusers/examples): fix bugs about to_float when fp32

---

examples/pixart_sigma/README.md
examples/pixart_sigma/gradio_demo.py
examples/pixart_sigma/pixart/lora-finetuning/inference_pixart_lora.py
examples/pixart_sigma/pixart/lora-finetuning/train_pixart_lora.py
examples/pixart_sigma/pixart/pipelines/infer_pipeline.py

1. Add gradio demo with difference options to change Sampling Methods, Sampling Steps and Guidance Scale.
2. Implement a cache to avoid re-creation of sampling fucntion in Inference pipeline.
3. Add LoRA for training and inference using diffusers.
4. Update README.md to include Mindone.diffusers integration and LoRA tutorial
@xxx

[Pixart-Sigma] ADD Gradio Demo, Diffuser Integration and LoRA finetuning

---

examples/diffusers/dreambooth/train_dreambooth.py
examples/diffusers/dreambooth/train_dreambooth_lora.py
mindone/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py

(cherry picked from commit ff3c32f8841928f84ea56ce6df453855f64545c1)
@xxx

fix(diffusers): fix some bugs (#797)

---

docs/diffusers/_toctree.yml
docs/diffusers/api/pipelines/auto_pipeline.md
docs/diffusers/api/pipelines/latte.md
docs/diffusers/api/pipelines/lumina.md
docs/diffusers/api/pipelines/stable_diffusion/stable_diffusion_3.md
docs/diffusers/tutorials/autopipeline.md
docs/diffusers/tutorials/using_peft_for_inference.md
docs/diffusers/using-diffusers/pag.md

feat(diffusers/docs): update docs of diffusers to v0.30.3

---

mindone/diffusers/_peft/peft_model.py
mindone/diffusers/_peft/tuners/lora/model.py

fix(diffusers): fix some bugs (prevent infinite recursion if class is not initialized)

---

examples/t2v_turbo/train_t2v_turbo_vc2.py

- fix the bug of `num_train_epochs` calculation when dealing with small dataset
@xxx

fix(t2v-turbo): fix the bug of `num_train_epochs`

---

mindone/diffusers/pipelines/kandinsky3/pipeline_kandinsky3_img2img.py
mindone/diffusers/pipelines/pag/pipeline_pag_sd_xl_img2img.py
mindone/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
mindone/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_instruct_pix2pix.py
mindone/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py

fix(diffusers): change "repeat" to "tile" uniformly

---

mindone/models/modules/parallel/conv.py
mindone/trainers/zero.py

zero fix a bug

---

mindone/diffusers/pipelines/pipeline_loading_utils.py

feat(mindone/diffusers): add custom importlib

---

mindone/trainers/zero.py

update ms_class to jit_class

---

examples/step_video_t2v/README.md
examples/step_video_t2v/requirement.txt
examples/step_video_t2v/requirements.txt
examples/step_video_t2v/stepvideo/diffusion/video_pipeline.py
examples/step_video_t2v/stepvideo/modules/model.py
examples/step_video_t2v/stepvideo/parallel.py

update stepvideo readme

---

mindone/diffusers/models/attention_processor.py
mindone/diffusers/schedulers/scheduling_euler_discrete.py

fix(diffusers): fix bugs of euler discrete scheduler and attention processor

---

mindone/transformers/generation/utils.py
mindone/transformers/modeling_utils.py

fix(transformers): generation config bugfix/time module deletion

---

docs/tools/zero.md
mindone/trainers/callback.py

fix callback & zero bugs

---

mindone/diffusers/models/model_loading_utils.py
mindone/diffusers/models/modeling_utils.py
mindone/diffusers/pipelines/pipeline_loading_utils.py
mindone/diffusers/pipelines/pipeline_utils.py

feat(diffusers): update the method of loading from v0.30.3 to v0.31.0

---

docs/diffusers/api/pipelines/cogview4.md
examples/cogview/README.md
examples/cogview/inference/cli_demo_cogview4.py

feat(examples/cogview): add cogview4

---

mindone/diffusers/models/attention_processor.py

fix(diffusers): fix the bug of attention_processor

---

mindone/diffusers/models/__init__.py
mindone/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion.py

fix(diffusers): fix bug that relies on torch

---

.hatch_metadata_hooks.py
CONTRIBUTING.md
mindone/__init__.py
mindone/version.py
pyproject.toml

`hatch-vcs`-like version name
```shell
pip install -e . && pip show mindone
```
Outputs:
```
Name: mindone
Version: 0.3.0.dev0+g66ce18a.d20250313
...
```
which means:
```
mindone-{base-version}+g{latest_commit}.d{latest_commit_date}  #PEP440
```
```shell
❯ hatch build
────────────────── sdist ────────────────────
dist/mindone-0.3.0.dev0+g66ce18a.d20250313.tar.gz
────────────────── wheel ───────────────────
dist/mindone-0.3.0.dev0+g66ce18a.d20250313-py3-none-any.whl
```
```toml
[tool.hatch.metadata.hooks.custom]
path = ".hatch_metadata_hooks.py"
base-version = "0.3.0.dev0"
build-type = "dev"  # ['dev', 'release']
```
Anyone in the community is …

feat: version with latest commit info

---

examples/diffusers/dreambooth/README_sd3.md
examples/diffusers/dreambooth/train_dreambooth_lora_sd3.py
examples/diffusers/dreambooth/train_dreambooth_sd3.py
mindone/diffusers/models/embeddings.py
mindone/diffusers/models/transformers/transformer_sd3.py
mindone/diffusers/training_utils.py

Update training scripts to support StableDiffusion3.5 finetune
> [!WARNING]
> This PR ​depends on diffusers 0.31.0 or a newer version, but the update has not yet been ​merged into the target branch. For details, please check with @Cui-yshoho 
@xxx

feat(sd3.5): Update training scripts to support StableDiffusion3.5 finetune

---

examples/diffusers/controlnet/README_flux.md
examples/diffusers/controlnet/train_controlnet_flux.py

add mindone.diffusers flux-controlnet training scripts to v0.30 branch.
@CaitinZhao

add flux-controlnet training

---

mindone/transformers/models/auto/auto_factory.py

… file
@CaitinZhao @SamitHuang @zhanghuiyao

fix(transformers): support automodel call for ModelClass in Modeling_ file

---

mindone/transformers/testing_utils.py
tests/transformers_tests/models/auto/test_modeling_auto.py
tests/transformers_tests/test_feature_extraction_common.py
tests/transformers_tests/test_image_processing_common.py
tests/transformers_tests/test_image_transforms.py
tests/transformers_tests/test_sequence_feature_extraction_common.py

@SamitHuang @CaitinZhao @zhanghuiyao

feat(transformers): tests for automodel/image processor/feature extractor

---

examples/hunyuanvideo/hyvideo/modules/__init__.py

fix bug of hunyuanvideo inference, param name changed from PR #834

Hunyuanvideo inference bugfix

---

mindone/transformers/__init__.py
mindone/transformers/models/clip/modeling_clip.py
mindone/transformers/models/qwen2/modeling_qwen2.py
mindone/transformers/requirements.txt
pyproject.toml

upgrade transformer version to 4.46.3

---

mindone/transformers/__init__.py
mindone/transformers/mindspore_adapter/clip_grad.py
mindone/transformers/modeling_utils.py
mindone/transformers/models/clip/modeling_clip.py
mindone/transformers/models/gpt2/__init__.py
mindone/transformers/models/qwen2/modeling_qwen2.py
mindone/transformers/requirements.txt
mindone/transformers/trainer.py
mindone/transformers/training_args.py
pyproject.toml
tests/transformers_tests/models/clip/test_modeling_clip.py

fix(transformers): fix bugs for transformers upgrade

---

tests/diffusers_tests/pipelines/cogvideo/test_cogvideox_image2video.py
tests/diffusers_tests/pipelines/cogvideo/test_cogvideox_video2video.py
tests/diffusers_tests/pipelines/controlnet_sd3/test_controlnet_inpaint_sd3.py
tests/diffusers_tests/pipelines/flux/test_pipeline_flux.py
tests/diffusers_tests/pipelines/flux/test_pipeline_flux_img2img.py
tests/diffusers_tests/pipelines/flux/test_pipeline_flux_inpaint.py
tests/diffusers_tests/pipelines/latte/test_latte.py
tests/diffusers_tests/pipelines/lumina/test_lumina_nextdit.py
tests/diffusers_tests/pipelines/pag/test_pag_animatediff.py

feat(diffusers/tests): add full test for pipelines in diffusers v0.30.3 and v0.31.0

---

examples/opensora_pku/README.md

Update the mindspore version in opensora-pku v1.3.0 from 2.3.1 to 2.5.0.

Opensora-PKU v1.3.0: update mindspore version to 2.5.0

---

examples/videocomposer/README.md
examples/videocomposer/train.py
examples/videocomposer/vc/annotator/depth/midas.py

1. Change `repeat` to `repeat_interleave` in `depth/midas.py`
2. The performance remains the same with MS 2.3.1
@xxx

Update VideoComposer to MS2.5

---

mindone/diffusers/models/transformers/transformer_cogview4.py

fix(diffusers/cogview4): resolve the issue of slow speed with graph

---

examples/story_diffusion/README.md
examples/story_diffusion/run.py

Update the mindspore version from 2.3.1 to 2.5.0.
The  inference results are good in ms 2.5.0.

StoryDiffusion: update to ms 2.5.0

---

examples/pixart_sigma/README.md

[README] PixArt Sigma to MS 2.5.0

---

examples/autoencoders/README.md
examples/autoencoders/args_train.py
examples/autoencoders/train.py
examples/venhancer/README.md

1. update venhancer based on ms2.5.
2.  autoencoders readme and use jit level O1 based on ms2.5.
@xxx

[README] update venhancer and autoencoders readme to ms2.5

---

examples/var/README.md
examples/var/script/run_train_d16.sh
examples/var/train.py
examples/var/utils/arg_utils.py
examples/var/utils/net_with_loss.py
examples/var/utils/utils.py

fix memory bug, now, var-d16 train batch size from 32 to 96.
@xxx

fix var memory bug

---

examples/wan2_1/wan/utils/prompt_extend.py
mindone/transformers/__init__.py
mindone/transformers/models/__init__.py

Since mindone.transformer need `transformer version == 4.46.3` while Qwen2.5VL needs  `transformer version >= 4.49.0`, it cause the incompatibility problem of module import
Here we simply comment out the module import of Qwen2.5VL in Mindone to avoid the import problem.
@xxx

[Bug Fix] Fix the import error for mindone transformer

---

examples/diffusers/controlnet/train_controlnet_flux.py

update flux-controlnet training script from diffusers v0.31  to v0.32.2

update flux-controlnet training script to diffusers v0.32.2

---

examples/sharegpt_4v/readme.md

Adds # 
Update read.me with MS2.5 env info.
@xxx

[Share_GPT4v] Update readme.md

---

mindone/utils/env.py

- Fixes bug in the `init_env` function that omits setting the execution mode.
@xxx

[Bug] Fix bug in env initialization

---

examples/diffusers/controlnet/train_controlnet_flux.py
examples/diffusers/dreambooth/train_dreambooth_lora_flux.py
mindone/diffusers/models/transformers/transformer_flux.py

update flux training script from diffusers v0.31 to v 0.32:
* flux-lora
* flux-controlnet

fix(diffusers/flux):update flux training script from v0.31 to v0.32

---

examples/openlrm/README.md

Update readme of OpenLRM training performance with mindspore 2.5.0: `examples/openlrm/README.md`
@SamitHuang

Update README of OpenLRM training w/ ms2.5.0

---

examples/opensora_pku/README.md

Revise readme file of Opensora-pku v.1.3.0

[Opensora-PKU]: revise readme file

---

examples/diffusers/controlnet/train_controlnet_flux.py
examples/diffusers/dreambooth/README_sdxl.md
examples/kohya_sd_scripts/README.md
examples/kohya_sd_scripts/library/train_util.py
examples/kohya_sd_scripts/train_network.py

1. update kohya script to ms2.5
2. fix readme and update performance
3. temp.fix: diffusers example sdxl edm training readme

[bugfix/v0.3.0 dev] update kohya sd script to ms2.5 and bugfix

---

pyproject.toml

Fix requirements

---

mindone/transformers/models/clip/modeling_clip.py

sync changes

---

docs/diffusers/api/pipelines/amused.md
docs/diffusers/api/pipelines/ledits_pp.md
mindone/diffusers/__init__.py
mindone/diffusers/models/normalization.py
mindone/diffusers/models/unets/uvit_2d.py
mindone/diffusers/pipelines/__init__.py
mindone/diffusers/pipelines/amused/__init__.py
mindone/diffusers/pipelines/amused/pipeline_amused.py
mindone/diffusers/pipelines/amused/pipeline_amused_img2img.py
mindone/diffusers/pipelines/amused/pipeline_amused_inpaint.py
mindone/diffusers/pipelines/ledits_pp/__init__.py
mindone/diffusers/pipelines/ledits_pp/pipeline_leditspp_stable_diffusion.py
mindone/diffusers/pipelines/ledits_pp/pipeline_leditspp_stable_diffusion_xl.py
mindone/diffusers/pipelines/ledits_pp/pipeline_output.py
mindone/diffusers/schedulers/__init__.py
mindone/diffusers/schedulers/scheduling_amused.py
mindone/diffusers/utils/mindspore_utils.py

feat(diffusers): add amused&ledits_pp

---

mindone/diffusers/__init__.py
mindone/diffusers/pipelines/__init__.py
mindone/diffusers/pipelines/text_to_video_synthesis/__init__.py
mindone/diffusers/pipelines/text_to_video_synthesis/pipeline_output.py
mindone/diffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_zero.py
tests/diffusers_tests/pipelines/text_to_video_synthesis/test_text_to_video_zero.py

[bugfix] fix bug in diffuers/pipeline/_init_

---

examples/opensora_pku/opensora/models/diffusion/opensora/modules.py

The function **PositionGetter3D** has a certain output when the input is certain. The purpose of this pr is to calculate this function when the processor is initialized to prevent subsequent double calculations.
Tests were conducted on MindSpore 2.5.0 with CANN 8.0.0.beta1. For OpenSoraPlan 1.3.0 training on stage3 t2v(93x352x640), performance is increased by 20%(8.8s/step -> 7s/step).
@xxx

Open-Sora performance optimization

---

examples/opensora_pku/opensora/dataset/t2v_datasets.py
examples/opensora_pku/opensora/train/train_t2v_diffusers.py
examples/opensora_pku/requirements.txt

When Decord is adapted for video processing, because get_fetch method from Decord takes too long, the data processing time of one step is often more than 8s, resulting in the computing time can not cover the data processing time.
This pr adapts PyAV to process video, which stabilizes the data processing time in 3-4s, and provides options for users to choose.
@xxx

PyAV adaptation for OpenSoraPlan 1.3

---

examples/opensora_pku/opensora/dataset/loader.py
examples/opensora_pku/opensora/train/commons.py
examples/opensora_pku/opensora/train/train_causalvae.py
examples/opensora_pku/opensora/train/train_t2v_diffusers.py

Provide dataset_iterator_no_copy option for OpenSoraPlan 1.3. When use --dataset_iterator_no_copy=True, dataset iterator will create a Tensor without copy which can speed up.
Tests were conducted on MindSpore 2.5.0 with CANN 8.0.0.beta1. For OpenSoraPlan 1.3.0 training on stage3 t2v(93x352x640), performance is increased by 1.1%(6.95s/step -> 6.87s/step).
@xxx

Provide dataset_iterator_no_copy option for OpenSoraPlan 1.3

---

examples/opensora_pku/opensora/models/causalvideovae/model/vae/modeling_wfvae.py
examples/opensora_pku/opensora/models/diffusion/common.py
examples/opensora_pku/opensora/models/diffusion/opensora/net_with_loss.py

Change ops.randn/ops.rand_like/ops.standard_normal/ops.arrage etc. to mint.
Tests were conducted on MindSpore 2.5.0 with CANN 8.0.0.beta1. For OpenSoraPlan 1.3.0 training on stage3 t2v(93x352x640), performance is increased by 3.9%(6.87s/step -> 6.6s/step).
@xxx

mint change in OpenSora Plan 1.3

---

mindone/diffusers/models/attention_processor.py
mindone/diffusers/models/embeddings.py
mindone/diffusers/models/normalization.py
mindone/diffusers/models/transformers/transformer_flux.py
mindone/diffusers/pipelines/flux/pipeline_flux.py
mindone/diffusers/pipelines/flux/pipeline_flux_controlnet.py

Replace slice to expand_dims/split which is faster for graph mode.
**Usage example**
```python
emb = timesteps[:, None].float() * emb[None, :] 
emb = timesteps.expand_dims(axis=1).float() * emb.expand_dims(axis=0) 
hidden_states = hidden_states[:, encoder_hidden_states.shape[1] :, ...] 
hidden_states = mint.split(
hidden_states,
[encoder_hidden_states.shape[1], hidden_states.shape[1] - encoder_hidden_states.shape[1]],
dim=1,
)[1]
```
@xxx

Flux: replace slice to expand_dims/split

---

examples/diffusers/controlnet/train_controlnet_flux.py
examples/diffusers/dreambooth/train_dreambooth_lora_flux.py
mindone/diffusers/models/embeddings.py

1. Provide dataset_iterator_no_copy option. When use --dataset_iterator_no_copy=True, dataset iterator will create a Tensor without copy which can speed up.
2. Provide jit_level option for Flux-LoRA.
3. Change the dtype of the repeat_interleave entry parameter from float64(AICPU) to float32(AICORE).
@xxx

Flux performance optimization

---

mindone/diffusers/utils/hub_utils.py

Fixes:
a little bug as the title says.
@xxx

fix(diffusers): fix bugs about checkpoints loading in `utils/hub_utils.py`

---

mindone/transformers/__init__.py
mindone/transformers/models/__init__.py
mindone/transformers/models/switch_transformers/__init__.py
mindone/transformers/models/switch_transformers/modeling_switch_transformers.py
tests/modeling_test_utils.py
tests/transformers_tests/models/switch_transformers/test_switch_transformers.py

Adds # (feature) Add switch transformers model and myt5 Tokenizer
@xxx

Add model switch transformers&myt5 Tokenizer

---

mindone/transformers/models/bart/modeling_bart.py
mindone/transformers/models/glm/modeling_glm.py
mindone/transformers/models/qwen2_audio/modeling_qwen2_audio.py

1  fix dtype bug
2 fix linear bug

fix dtype bug & Linear bug

---

mindone/diffusers/models/modeling_utils.py
mindone/diffusers/pipelines/unidiffuser/modeling_text_decoder.py
mindone/diffusers/pipelines/unidiffuser/pipeline_unidiffuser.py

unidiffuser shared weight bugfix

---

docs/diffusers/api/normalization.md
mindone/diffusers/models/autoencoders/autoencoder_kl_allegro.py
mindone/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py
mindone/diffusers/models/autoencoders/autoencoder_kl_mochi.py
mindone/diffusers/models/autoencoders/autoencoder_kl_temporal_decoder.py
mindone/diffusers/models/normalization.py
mindone/diffusers/models/transformers/hunyuan_transformer_2d.py
mindone/diffusers/models/transformers/transformer_flux.py
mindone/diffusers/models/unets/unet_1d_blocks.py

Replace internal GroupNorm with mint GroupNorm

---

examples/hunyuan_dit/hydit/data_loader/csv2arrow.py
examples/opensora_pku/opensora/models/causalvideovae/eval/fvd/styleganv/fvd.py
examples/opensora_pku/opensora/models/causalvideovae/eval/fvd/videogpt/fvd.py
examples/stable_diffusion_v2/ldm/data/sync_data.py
examples/stable_diffusion_v2/tests/st/test_train_infer_dummy.py
examples/stable_diffusion_v2/tools/eval/fid/utils.py
examples/stable_diffusion_v2/utils/download.py
examples/stable_diffusion_xl/tools/rank_table_generation/hccl_tools.py
examples/t2v_turbo/utils/download.py
examples/venhancer/inference_utils.py
examples/videocomposer/tools/data_converter.py
examples/videocomposer/tools/gen_frames.py
examples/videocomposer/vc/utils/download.py
mindone/models/threestudio/models/prompt_processors/base.py
tools/data/webvid_scripts/datacheck_webvid.py
tools/data/webvid_scripts/divide_parts.py
tools/modelarts/msrun/msrun.py
tools/t2v_curation/script/pipeline_runner.py

Fix code safety check

---

examples/animatediff/tests/test_mm.py
examples/hunyuan_dit/IndexKits/index_kits/dataset/config_parse.py
examples/hunyuanvideo/tests/parallel/compare_batch_data.py
examples/hunyuanvideo/tests/parallel/test_sequence_parallel_data.py
examples/instantmesh/README.md
examples/instantmesh/configs/instant-nerf-large-train.yaml
examples/instantmesh/data/objaverse.py
examples/opensora_pku/opensora/dataset/t2v_datasets.py
examples/opensora_pku/opensora/eval/cal_ssim.py
examples/opensora_pku/opensora/models/causalvideovae/model/registry.py
examples/pangu_draw_v3/gm/lr_scheduler.py
examples/pangu_draw_v3/gm/modules/diffusionmodules/util.py
examples/pixart_sigma/pixart/diffusers/models/autoencoders/autoencoder_kl.py
examples/pixart_sigma/pixart/diffusers/models/autoencoders/vae.py
examples/sv3d/configs/sv3d_u_train.yaml
examples/sv3d/data/mulvideo_dataset.py
examples/t2v_turbo/README.md
examples/t2v_turbo/predict_t2v.py
examples/t2v_turbo/tools/convert_weights.py
examples/t2v_turbo/train_t2v_turbo_vc2.py
examples/t2v_turbo/utils/lora.py
examples/transformers/qwen2_5_omni/README.md
examples/videocomposer/tools/pt2ms.py
examples/videocomposer/vc/utils/pt2ms.py
mindone/tools/sd_torch_to_mindspore/np2ms_v1.py
mindone/tools/sd_torch_to_mindspore/np2ms_v2.py
mindone/tools/sd_torch_to_mindspore/pt2np_v1.py
mindone/tools/sd_torch_to_mindspore/pt2np_v2.py
mindone/transformers/models/qwen2_5_omni/convert_spk_dict_pt2np.py
mindone/transformers/models/qwen2_5_omni/modeling_qwen2_5_omni.py

Master fix pickle

---

mindone/transformers/modeling_utils.py
mindone/transformers/models/auto/configuration_auto.py
mindone/transformers/models/auto/modeling_auto.py
mindone/transformers/models/glm/modeling_glm.py
mindone/transformers/models/qwen2/modeling_qwen2.py
mindone/transformers/models/qwen3/modeling_qwen3.py

fix(transformers): fix issues in transformers to support vLLM

---

examples/moviegen/tools/download_convert_st.py
examples/opensora_hpcai/tools/download_convert_st.py
examples/pixart_sigma/gradio_demo.py
examples/stable_diffusion_v2/tools/eval/fid/utils.py
examples/stable_diffusion_v2/tools/safety_checker/utils.py
examples/stable_diffusion_v2/utils/download.py
examples/step_video_t2v/api/call_remote_server.py
examples/story_diffusion/gradio_app_sdxl_specific_id_low_vram.py.py
examples/t2v_turbo/utils/download.py
examples/transformers/kimi_vl/generate.py
examples/transformers/qwen2_5_vl/generate.py
examples/transformers/qwen2_5_vl/generate_batch.py
examples/videocomposer/vc/utils/download.py
examples/wan2_1/gradio/t2v_1.3B_singleNPU.py

Fix security issues

---

examples/opensora_hpcai/opensora/models/vae/vae.py
examples/step_video_t2v/api/call_remote_server.py
tools/t2v_curation/pipeline/splitting/cut.py

clean code

---

mindone/transformers/models/t5/modeling_t5.py

support graph mode for t5

---

tests/transformers_tests/models/idefics3/test_modeling_idefics3.py
tests/transformers_tests/models/qwen2_5_omni/test_modeling_qwen2_5_omni.py

- Fixed UT errors that occurred in idefics3 and qwen2.5-omni

fix UT error in idefics3 and qwen2.5-omni

---

examples/transformers/qwen2_vl/README.md
examples/transformers/qwen2_vl/video_understanding.py
examples/transformers/qwen2_vl/vqa_test.py
mindone/transformers/modeling_utils.py
mindone/transformers/models/llama/modeling_llama.py
mindone/transformers/models/qwen2_vl/modeling_qwen2_vl.py
tests/transformers_tests/models/qwen2_vl/test_modeling_qwen2_vl.py

- upgraded Qwen2-VL to transformers 4.50.0
- tested with mindspore 2.6.0

[transformers] upgrade Qwen2-VL to transformers 4.50.0

---

examples/lang_sam/README.md
examples/lang_sam/README_CN.md
examples/lang_sam/checkpoints/download_ckpts.sh
examples/lang_sam/lang_sam/__init__.py
examples/lang_sam/lang_sam/lang_sam.py
examples/lang_sam/lang_sam/models/gdino.py
examples/lang_sam/lang_sam/models/sam.py
examples/lang_sam/lang_sam/utils.py
examples/lang_sam/predict_image.py
examples/lang_sam/requirements.txt

Inference support:
1. predict bounding bbox, segmentation map prediction given a static image and a text prompt.

[feature] Add Language SAM to examples

---

docs/diffusers/using-diffusers/merge_loras.md

This small PR fixes the LoRAs reference. Relevant page: https://mindspore-lab.github.io/mindone/0.3/diffusers/using-diffusers/merge_loras/

fix: update LoRAs reference

---

examples/animatediff/README.md

- Updated the performance data of 2.6.0 and 2.7.0.
@xxx

update animatediff readme

---

mindone/transformers/models/bart/modeling_bart.py
mindone/transformers/models/fuyu/modeling_fuyu.py
mindone/transformers/models/gemma/modeling_gemma.py
mindone/transformers/models/gemma3/modeling_gemma3.py
mindone/transformers/models/granite/modeling_granite.py
mindone/transformers/models/granitemoe/modeling_granitemoe.py
mindone/transformers/models/granitemoeshared/modeling_granitemoeshared.py
mindone/transformers/models/mixtral/modeling_mixtral.py
mindone/transformers/models/paligemma/modeling_paligemma.py
mindone/transformers/models/persimmon/modeling_persimmon.py
mindone/transformers/models/qwen2_audio/modeling_qwen2_audio.py
mindone/transformers/models/recurrent_gemma/modeling_recurrent_gemma.py
mindone/transformers/models/roberta/modeling_roberta.py
mindone/transformers/models/siglip/modeling_siglip.py
tests/transformers_tests/models/recurrent_gemma/test_modeling_recurrent_gemma.py

1 fix example bug
2 fix qwen2_audio UT error

fix(transformers)fix example bug and qwen_audio UT bug

---

examples/transformers/myt5/README.md

added usage examples in myt5 readme examples/transformers/myt5/README.md
Experiments are tested on Ascend Atlas 800T A2 machines with mindspore 2.6.0.
|model|mode|weight loading time(s)|speed(ms/step)|
|:--:|:--:|:--:|:--:|
|Tomlim/myt5-small|pynative|49|120.04|
|Tomlim/myt5-base|pynative|97|158.97|
|Tomlim/myt5-large|pynative|215|304.75|
@xxx

Add MyT5 usage examples
