examples/stable_diffusion_v2/eval/clip_score/utils/__init__.py, examples/stable_diffusion_v2/eval/clip_score/utils/compute_metrics.py, examples/stable_diffusion_v2/eval/eval_clip_score.py
The file `compute_torch.py` was not included in my previous commits for the clip-score PR. This is because `.gitignore` includes `*torch*.py`. I renamed the file and now `eval_clip_score.py` should work fine.
=> add missing file for clip score

examples/stable_diffusion_v2/ldm/modules/train/optim.py, examples/stable_diffusion_v2/scripts/run_train_v2.sh, examples/stable_diffusion_v2/train_dreambooth.py, examples/stable_diffusion_v2/train_text_to_image.py
- Previous bug:  
weight decay is fixed to **1e-6**  
The reference value used in LAION training or LoRA fine-tune in diffusers is 1e-2 
- Fix in this PR:  weight decay is now configurable via arg parser.
Now default weight decay is  **1e-2**
=> Make weight decay configurable and change default value

examples/stable_diffusion_v2/README.md, examples/stable_diffusion_v2/inpaint.py, examples/stable_diffusion_v2/ldm/modules/lora.py, examples/stable_diffusion_v2/lora_finetune.md, examples/stable_diffusion_v2/scripts/run_text_to_image_v2_lora.sh, examples/stable_diffusion_v2/scripts/run_train_v2_lora.sh, examples/stable_diffusion_v2/tests/test_lora.py, examples/stable_diffusion_v2/text_to_image.py, examples/stable_diffusion_v2/train_text_to_image.py
prev: LoRA finetune is only applied to UNet
cur: allow LoRA fine-tune both/either UNet and/or text encoder
=> Add LoRA finetuning for TextEncoder; Fix bugs

examples/videocomposer/vc/engine/inference_single.py
=> videocomposer fix bug

examples/stable_diffusion_v2/dreambooth_finetune.md, examples/stable_diffusion_v2/scripts/run_train_dreambooth_w_lora_sd_v2.sh, examples/stable_diffusion_v2/train_dreambooth.py
=> dreambooth plus lora

examples/stable_diffusion_v2/adapter_image2image.py, examples/stable_diffusion_v2/adapters/__init__.py, examples/stable_diffusion_v2/adapters/t2i_adapter.py
Moved all operations on tensors (multiplication, concatenation, etc.) under `construct()` to improve inference speed.
=> accelerate T2I-Adapter inference

examples/videocomposer/README.md, examples/videocomposer/configs/train_exp02_motion_transfer.yaml, examples/videocomposer/configs/train_exp02_motion_transfer_vs_style.yaml, examples/videocomposer/configs/train_exp03_sketch2video_style.yaml, examples/videocomposer/configs/train_exp04_sketch2video_wo_style.yaml, examples/videocomposer/configs/train_exp05_text_depths_wo_style.yaml, examples/videocomposer/configs/train_exp06_text_depths_vs_style.yaml, examples/videocomposer/run_train.sh, examples/videocomposer/run_train_distribute.sh, examples/videocomposer/train.py, examples/videocomposer/vc/annotator/canny/__init__.py, examples/videocomposer/vc/annotator/depth/midas.py, examples/videocomposer/vc/config/parser.py, examples/videocomposer/vc/data/dataset_train.py, examples/videocomposer/vc/diffusion/latent_diffusion.py, examples/videocomposer/vc/engine/inference_single.py, examples/videocomposer/vc/utils/misc.py, examples/videocomposer/vc/utils/visualization.py
[result.log](https://raw.githubusercontent.com/wtomin/mindone-assets/main/videocomposer-assets/results/train_depth_results.txt) for `train_exp06_text_depth_vs_style.yaml` exp; 
Not sure if the loss is oscillating too much.
=> Videocomposer training

examples/videocomposer/vc/config/parser.py
Since `vc/config/parser.py` has changed in #159 , any argument without a default value will be treated as None, which is not going to be updated in `cfg`. This can cause ` cfg.style_image no attribute error` in `vc/engine/inference_single.py`. Like `--sketch_path` an d `--image_path`, `--style_image` should have a default value.
=> correct cfg.style_image no attribute error

examples/videocomposer/vc/annotator/depth/midas.py, examples/videocomposer/vc/config/base.py, examples/videocomposer/vc/models/attention.py, examples/videocomposer/vc/models/stc_encoder.py, examples/videocomposer/vc/models/unet_sd.py
Change some operators to fp32 calculation implicitly instead, for preventing certain bug (e.g, `to_float` in Conv3d and GroupNorm)
=> Change some operators to fp32 calculation implicitly 

examples/videocomposer/vc/models/attention.py
Remove `.transpose` and `.reshape` before and after groupnorm in temporal blocks (`TemporalAttentionBlock` and `TemporalTransformer`), since `GroupNorm` supports flattening the dimensions starting from `3`.
=> temporal groupnorm fix error

examples/videocomposer/vc/data/dataset_train.py, examples/videocomposer/vc/data/datasets.py
A minor change to avoid the error of not finding `annotator` when `export MS_COMPILER_CACHE_ENABLE=1`. This bug will be fixed in future mindspore version.
=> videocomposer: change relative import .. in dataset

examples/stable_diffusion_v2/dreambooth_finetune.md, examples/stable_diffusion_v2/tools/model_conversion/convert_weights.py
=> DreamBooth: convert existing DB weight and run inference

examples/stable_diffusion_v2/tools/eval/fid/utils.py
When using the torch backend to eval fid, it is necessary to first resize the image to the same size.
=> fix eval fid bug in torch backend

examples/stable_diffusion_v2/README.md, examples/stable_diffusion_v2/demo.md, examples/stable_diffusion_v2/text_to_image.py, examples/stable_diffusion_v2/utils/long_prompt.py, examples/stable_diffusion_xl/GETTING_STARTED.md, examples/stable_diffusion_xl/demo/sampling.py, examples/stable_diffusion_xl/demo/sampling_without_streamlit.py, examples/stable_diffusion_xl/gm/util/long_prompt.py
Support long prompt (without truncating the text prompts to context length) by dividing the long prompt into groups of shorter prompts.
See `args.support_long_prompts` and `utils/long_prompt.py` for details.
=> SD V2 and SD-XL: support long prompts

examples/stable_diffusion_xl/demo/sampling.py, examples/stable_diffusion_xl/textual_inversion_finetune.md
As the title suggests, 
1. allow specifying the textual inversion weight file in ` demo/sampling.py`;
2. fix some equation expression errors in the textual inversion readme file.
=> SD-XL Textual Inversion: allow demo/sampling.py to use textual inversion and readme fix

examples/stable_diffusion_xl/gm/helpers.py, examples/stable_diffusion_xl/train.py, examples/stable_diffusion_xl/train_dreambooth.py
The sdxl ckpt files are too large (~13GB each) to save in local server especially `args.save_ckpt_interval` is set to be a small value. We can keep the latest `args.max_num_ckpt` ckpt files and delete those old ones. Keep all ckpts when `args.max_num_ckpt` is 0.
=> Add checkpoint deletion feature to SDXL

examples/stable_diffusion_v2/ldm/data/dataset_refactored.py, examples/t2i_adapter/configs/sd_v2.1_train.yaml, examples/t2i_adapter/data/dataset_with_cond.py, examples/t2i_adapter/train_t2i_adapter_sd.py, mindone/data/__init__.py, mindone/data/dataset.py, mindone/data/loader.py
This PR introduces native support for the MindData pipeline, building upon our successful experiments in the MindOCR project (https://github.com/mindspore-lab/mindocr/pull/416). Our experiments showed that this pipeline not only simplifies the development process through modularization but also improves training speed by **up to 3 times**.
However, as the native pipeline integration occurred during the late stages of MindOCR development, the process was quite challenging, and the PR has not yet been merged. To prevent similar problems in MindONE, I strongly recommend adopting the new pipeline as early as possible.
**The idea is as follows:** each dataset in MindONE should inherit from the `BaseDataset` class, define the required attribute `output_columns`, and implement the abstract …
=> improve data pipeline by adding MindData native support

examples/stable_diffusion_xl/demo/sampling_without_streamlit.py, examples/stable_diffusion_xl/gm/helpers.py
Support generating multiple samples via one prompt and concatenating them into a single image. 
P.S. In the new version of MindSpore 2.2.10 (released after 2023-12-12), enlarging the batch size for batch generation may lead to unknown result. Therefore, we have implemented this feature using a for loop.
=> [sdxl] concated multi-samples via one prompt

examples/stable_diffusion_v2/README.md, examples/stable_diffusion_v2/configs/v1-inference.yaml
Because of the risk of oom on 910A of sdv1.5+ FA, we should change the default setting and leave the option to the user.
=> SD V1.5: disable Flash-attention by default

examples/stable_diffusion_v2/configs/v2-vpred-inference-unclip-h.yaml, examples/stable_diffusion_v2/configs/v2-vpred-inference-unclip-l.yaml, examples/stable_diffusion_v2/configs/v2-vpred-inference.yaml, examples/stable_diffusion_v2/ldm/models/diffusion/ddim.py, examples/stable_diffusion_v2/ldm/models/diffusion/ddpm.py, examples/stable_diffusion_v2/ldm/modules/encoders/modules.py, examples/stable_diffusion_v2/text_to_image.py, examples/stable_diffusion_v2/unclip_image_variation.py
- Fix the unclip inference on 910/910* due to recent PRs changes
- Add DDIM v-pred support for text-to-image and unclip-image-variation, since DDIM is usually served as a benchmark for result comparison.
=> fix unclip inference and add ddim v-pred support

examples/animatediff/tools/embedding_cache.py, examples/animatediff/train.py, examples/dit/train.py, examples/stable_diffusion_v2/train_dreambooth.py, examples/videocomposer/analyze_video_frames.py, examples/videocomposer/analyze_video_meta.py, examples/videocomposer/train.py
MindSpore context [`max_device_memory`](https://www.mindspore.cn/docs/zh-CN/master/api_python/mindspore/mindspore.set_context.html#mindspore.set_context) can NOT be set after [`init()`](https://www.mindspore.cn/docs/zh-CN/master/api_python/mindspore.communication.html) while running in distributed mode. Otherwise error below raises:
```
Traceback (most recent call last):
File "/home/ma-user/modelarts/user-job-dir/mindone/examples/animatediff/train.py", line 510, in <module>
main(args)
File "/home/ma-user/modelarts/user-job-dir/mindone/examples/animatediff/train.py", line 188, in main
max_device_memory=args.max_device_memory,
File "/home/ma-user/modelarts/user-job-dir/mindone/examples/animatediff/train.py", line 173, in init_env …
```
=> Fix bug when ms.set_context(max_device_memory="xxGB")

examples/stable_diffusion_xl/tools/model_conversion/convert_diffusers_to_mindone_sdxl.py, examples/stable_diffusion_xl/tools/model_conversion/convert_weight.py
Parameter `conditioner.embedders.1.model.text_projection` is called differently in MindONE and Diffusers, so it is transposed when pre-trained weight is converted
**DETAIL:**
diffusers: 
```pooled_text_embedding = self.text_projection(input)```, where `self.text_projection` is a `torch.nn.Linear` without bias, which means `pooled_text_embedding = input @ self.text_projection.weight.T`
MindONE (and stability-AI):
```pooled_text_embedding = input @ self.text_projection.weight```, where **no transpose op**.
so we transpose this parameter manually when convert weights. …
=> SDXL: transpose `text_projection` in converting

examples/diffusers/text_to_image/README_sdxl.md, examples/diffusers/text_to_image/train_text_to_image_sdxl.py, mindone/diffusers/models/attention_processor.py, mindone/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py
- 30x faster training of diffusers-style sdxl by removing redundancy `ops.randn`. `ops.randn` runs on aicpu which is extremely slow.
- add data sinking
- fix fake progress bar can't exit if there are errors when compling
- support webdataset w/o streaming by huggingface/datasets
- fix some typos
@xxx
=> perf(diffusers/sdxl): speedup sdxl training by removing redundancy `ops.randn`

mindone/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py, mindone/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, mindone/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py
In pipelines for img2img, inpainting and other tasks using images as inputs (such as `StableDiffusionImg2ImgPipeline`), image inputs would be encoded into a gaussian distribution by `pipeline.vae.encode()`, then pipelines would use `retrieve_latents()` function to sample a deterministic latent tensor from this distribution. `retrieve_latents()` offers parameter `sample_mode` to select the method of sampling latent tensor.
Argument `sample_mode="argmax"` is supposed to mean that $$latents = \mathop{argmax}\limits_{x}\ P_z(x)$$
,where $P_z$ is the probility of encoded gaussian distribution, which means latents is the mean of the distribution in this case. Therefore the origin codes should be corrected to:
```diff
def retrieve_latents(vae, encoder_output: ms.Tensor, sample_mode: str = …
```
=> fix(diffusers/pipelines): fix vae encoding in pipelines

mindone/diffusers/models/attention_processor.py, mindone/diffusers/models/resnet.py
Fixes bugs in `mindone.diffusers.models`:
Existing additional arguments used in `nn.Cell.construct()` such as `*args` raise errors in static graph mode, therefore we remove all these arguments as they are not used actually.
These modules are affected:
- `AttnAddedKVProcessor` (in mindone.diffusers.models.attention_processor.py)
- `ResnetBlockCondNorm2D` (in mindone.diffusers.models.resnet.py)
@xxx
=> fix(diffusers/layers): remove additional arguments used in construct()

examples/opensora_pku/opensora/models/diffusion/latte/modeling_latte.py, examples/opensora_pku/opensora/models/diffusion/latte/modules.py, examples/opensora_pku/opensora/sample/sample_t2v.py, examples/opensora_pku/opensora/sample/sample_text_embed.py
FlashAttention in MindSpore only accepts mask with (0, 1), where 0 means to keep, and 1 means to discard.
Editing the current Opensora-PKU attention mask:
1. comment the code to fill in mask with `-ms.numpy.inf` in `LatteT2V.construct`;
2. Flip the mask using `1 - mask` since FA treats 1 as discard, 0 as retain.
3. Fill in with `-ms.numpy.inf` in vanilla Attention, and leave the mask untouched for FA
Minor changes: 
1. Print `Use FA` in `sample_t2v.py`;
2. Force tensor to fp32 before saving to `npz` in  `sample_text_embed.py`.
=> Opensora-PKU: fix fa attention mask

examples/opensora_pku/README.md, examples/opensora_pku/opensora/models/diffusion/latte/modeling_latte.py, examples/opensora_pku/opensora/models/diffusion/utils/pos_embed.py, examples/opensora_pku/opensora/sample/sample_t2v.py, examples/opensora_pku/opensora/train/train_t2v.py, examples/opensora_pku/scripts/text_condition/train_videoae_65x512x512.sh, examples/opensora_pku/scripts/text_condition/train_videoae_65x512x512_img16.sh
To improve speed, some modifications are made:
1. Skip attention_mask_compress if `compress_kv_factor` is 1;
2. Set vae to fp16 in `train_t2v.py` using the argument `vae_precision`;
3. Using `vae_keep_gn_fp32` to allow `nn.GroupNorm` in `custom_fp32_cells`. Defaults to `False`. It is verified by its inference quality. The training experiment with this commit is visually fine.
Some minor changes:
1. Printing message refinement.
2. `ProfilerCallback` changes to `ProfilerCallbackEpoch`
=> OpenSora-PKU v1.1: training speed improvement

examples/opensora_pku/README.md, examples/opensora_pku/docs/performance_boosting_history.md, examples/opensora_pku/docs/training_args.md, examples/opensora_pku/opensora/acceleration/communications.py, examples/opensora_pku/opensora/dataset/image_dataset.py, examples/opensora_pku/opensora/dataset/t2v_dataset.py, examples/opensora_pku/opensora/dataset/text_dataset.py, examples/opensora_pku/opensora/models/ae/videobase/causal_vae/modeling_causalvae.py, examples/opensora_pku/opensora/models/ae/videobase/dataset_videobase.py, examples/opensora_pku/opensora/models/diffusion/latte/modeling_latte.py, examples/opensora_pku/opensora/models/diffusion/latte/modules.py, examples/opensora_pku/opensora/sample/pipeline_videogen.py, examples/opensora_pku/opensora/train/commons.py, examples/opensora_pku/opensora/train/train_causalvae.py, examples/opensora_pku/opensora/train/train_t2v.py, examples/opensora_pku/requirements.txt, examples/opensora_pku/scripts/text_condition/train_videoae_17x512x512.sh, examples/opensora_pku/scripts/text_condition/train_videoae_221x512x512_sp.sh, examples/opensora_pku/scripts/text_condition/train_videoae_513x512x512_sp.sh, examples/opensora_pku/scripts/text_condition/train_videoae_65x512x512.sh, examples/opensora_pku/scripts/text_condition/train_videoae_65x512x512_img16.sh, examples/opensora_pku/scripts/text_condition/train_videoae_65x512x512_single_device.sh, examples/opensora_pku/scripts/text_condition/train_videoae_65x512x512_sp.sh
To accelerate training speed, major changes are made:
1. Update CANN version ([CANN C18(0517)](https://repo.mindspore.cn/ascend/ascend910/20240517/)->[CANN C18(0705)](https://repo.mindspore.cn/ascend/ascend910/20240705/)) and MindSpore version ([MS2.3_master(0615)](https://repo.mindspore.cn/mindspore/mindspore/version/202406/20240615/master_20240615020018_43ccb91e45899b64fe31d304497ab17e3ada3cea_newest/unified/) -> [MS2.3_master(0705)](https://repo.mindspore.cn/mindspore/mindspore/version/202407/20240705/master_20240705220018_51f414917fd9a312dd43ea62eea61cf37c3dfbd6_newest/unified/)); inference results on the new versions are visually fine. The overfitting experiment generates reasonable results.
2. Enable optimizer parallelism fusion by default (See `enable_parallel_fusion` in train …
=> OpenSora-pku v1.1: improve training speed and documents

examples/stable_diffusion_xl/gm/modules/transformers/transformers.py
fix scaled_dot_product_attention api dtype bug, or "TypeError: for primitive [BatchMatMul] input type must be same" if configure decoder_attn_dtype=fp16 in first_stage_config.
```
first_stage_config:
target: gm.models.autoencoder.AutoencoderKLInferenceWrapper
params:
...
decoder_attn_dtype: fp16
```
=> sdxl bug-fix: scaled_dot_product_attention api dtype

examples/opensora_hpcai/scripts/inference.py, examples/opensora_hpcai/scripts/train.py
During code refactoring for OpenSora v1.2, the `input_sq_size` argument for OS v1.1 was mistakenly removed (#561 #579). This PR fixes this issue.
=> [OpenSora v1.1] fix input sequence size

examples/opensora_pku/opensora/utils/ms_utils.py
Correct an environment error, caused by incorrect rank id and device id in single-device inference/training.
=> Open-Sora-PKU: correct rank id error

examples/animatediff/README.md
=> update doc for animatediff

tools/modelarts/README.md, tools/modelarts/msrun/run_train_modelarts.sh
In cloud training launched by `msrun`, if the MindSpore needs to be updated, users can `export ms_whl=[PATH_TO_MINDSPORE_WHL_FILE]` without rebuilding and uploading the whole docker again.
=> Support update MindSpore version on the fly in cloud training launch

examples/opensora_pku/README.md, examples/opensora_pku/examples/rec_video_folder.py, examples/opensora_pku/opensora/eval/eval_common_metrics.py, examples/opensora_pku/opensora/models/causalvideovae/model/causal_vae/modeling_causalvae.py, examples/opensora_pku/opensora/models/causalvideovae/model/losses/discriminator.py, examples/opensora_pku/opensora/models/causalvideovae/model/losses/net_with_loss.py, examples/opensora_pku/opensora/models/causalvideovae/model/modules/conv.py, examples/opensora_pku/opensora/train/train_causalvae.py, examples/opensora_pku/scripts/causalvae/eval.sh, examples/opensora_pku/scripts/causalvae/train_with_gan_loss.sh, examples/opensora_pku/scripts/causalvae/train_with_gan_loss_multi_device.sh, examples/opensora_pku/scripts/causalvae/train_without_gan_loss_multi_device.sh
Support training causalvae with full precision while using recompute. 
The training step time is 5.45s. The SSIM and PSNR scores are 0.88 and 29.28. The loss is converging normally for over 40k steps.
=> [Open-Sora-Plan-v1.2.0]: VAE training update

mindone/transformers/__init__.py, mindone/transformers/models/__init__.py, mindone/transformers/models/gemma2/__init__.py, mindone/transformers/models/gemma2/modeling_gemma2.py, pyproject.toml, tests/transformers_tests/models/gemma/test_modeling_gemma.py, tests/transformers_tests/models/gemma2/test_modeling_gemma2.py
[-Gemma2 report-](https://gist.github.com/townwish4git/0a7995ed154fba53e3f46fd7ac26fb53)
Add Gemma2 to MindONE transformers, for MindONE diffusers text-encoder
@xxx
=> feat(transformers): add GEMMA2

docs/index.md, docs/tools/_toctree.yml, docs/tools/zero.md, examples/opensora_pku/opensora/train/train_t2v_diffusers.py, examples/opensora_pku/tools/ckpt/combine_ckpt.py, mindone/diffusers/training_utils.py, mindone/models/modules/parallel/__init__.py, mindone/models/modules/parallel/conv.py, mindone/models/modules/parallel/dense.py, mindone/models/modules/parallel/param_wrapper.py, mindone/trainers/callback.py, mindone/trainers/zero.py, tests/others/test_zero.py
=> zero doc & checkpoint save adapt

examples/dynamicrafter/README.md, examples/dynamicrafter/configs/inference_1024_v1.0.yaml, examples/dynamicrafter/configs/inference_256_v1.0.yaml, examples/dynamicrafter/configs/inference_512_v1.0.yaml, examples/dynamicrafter/lvdm/models/ddpm3d.py, examples/dynamicrafter/lvdm/models/samplers/ddim.py, examples/dynamicrafter/lvdm/modules/attention.py, examples/dynamicrafter/lvdm/modules/encoders/condition.py, examples/dynamicrafter/lvdm/modules/encoders/resampler.py, examples/dynamicrafter/lvdm/modules/networks/openaimodel3d.py, examples/dynamicrafter/lvdm/modules/networks/util.py, examples/dynamicrafter/requirements.txt, examples/dynamicrafter/scripts/inference.py, examples/dynamicrafter/scripts/run/run_infer.sh, examples/dynamicrafter/tools/ms_param_256.txt, examples/dynamicrafter/tools/ms_param_512_1024.txt, examples/dynamicrafter/utils.py, examples/stable_diffusion_xl/gm/modules/embedders/modules.py, examples/stable_diffusion_xl/gm/modules/embedders/open_clip/model.py, examples/stable_diffusion_xl/gm/modules/embedders/open_clip/transformer.py, mindone/models/modules/flash_attention.py
mint op adaptation for dynamicrafter, run on mindspore 2.5.0
@xxx
=> Dynamicrafter: mint op adaptation

examples/hunyuan3d_1/README.md, examples/hunyuan3d_1/requirements.txt, examples/hunyuan3d_1/svrm/ldm/modules/rendering_neus/utils/renderer.py, examples/openlrm/README.md
Fixes # (issue) 
1. Hunyuan3D-1.0, see `examples\hunyuan3d_1`
-  README added mindspore 2.4.1 and mindspore 2.5.0 multiview to 3D inference performance; currently single image to multi-views does not support either ms2.4.1 or ms.2.5.0.
- Fixed minor bugs (e.g. requirements.txt)
2. OpenLRM README added mindspore 2.5.0 performance, see `examples/openlrm`
@SamitHuang
=> Update README for Hunyuan3D-1.0 and OpenLRM

examples/autoencoders/train.py, examples/dit/train.py, examples/emu3/emu3/train/train_seq_parallel.py, examples/fit/train.py, examples/hunyuanvideo/scripts/train.py, examples/hunyuanvideo/scripts/train_vae.py, examples/instantmesh/train.py, examples/latte/train.py, examples/moviegen/scripts/args_train_tae.py, examples/moviegen/scripts/eval_tae.py, examples/moviegen/scripts/gradio_demo.py, examples/moviegen/scripts/inference.py, examples/moviegen/scripts/inference_tae.py, examples/moviegen/scripts/inference_text_enc.py, examples/moviegen/scripts/train.py, examples/moviegen/scripts/train_tae.py, examples/mvdream/MVDream-threestudio/launch.py, examples/openlrm/openlrm/runners/train/lrm.py, examples/opensora_hpcai/scripts/v2.0/inference_v2.py, examples/opensora_hpcai/scripts/v2.0/text_embedding.py, examples/sv3d/train.py, examples/svd/train.py, examples/t2i_adapter/adapter_image2image_sdxl.py, examples/t2i_adapter/train_t2i_adapter_sd.py, examples/var/inference_demo.py, examples/var/train.py, examples/var/zero_shot_edit_demo.py, mindone/utils/__init__.py, mindone/utils/env.py
This PR:
- Updates the environment initialization function to support MS2.5.
- Renames the function from `init_train_env` to `init_env`, as it is used for both training and inference.
=> [Refactor] Update MindSpore environment initialization function to support MS2.5

mindone/transformers/integrations/sdpa_attention.py, mindone/utils/weight_norm.py, tests/modeling_test_utils.py, tests/transformers_tests/integrations/test_sdpa_attention.py, tests/transformers_tests/models/xlm_roberta_xl/test_modeling_xlm_roberta_xl.py
</p>
<hr>
<h1>SDPA Issues</h1>
`mindspore.ops.speed_fusion_attention` is **not equivalent** to `torch.nn.functional.scaled_dot_product_attention`.  
Currently, PyTorch's `scaled_dot_product_attention` supports three implementations:
1. **[FlashAttention-2: Faster Attention with Better Parallelism and Work Partitioning](https://arxiv.org/abs/2307.08691)**
2. **[Memory-Efficient Attention](https://github.com/facebookresearch/xformers)**
3. A **C++ PyTorch implementation** matching the standard formulation.
> If the user requires a specific fused implementation, the C++ PyTorch implementation can be disabled via [`torch.nn.attention.sdpa_kernel()`](https://docs.pytorch.org/docs/stable/generated/torch.nn.attention.sdpa_kernel.html#torch.nn.attention.sdpa_kernel).
`ops.speed_fusion_attention` …
=> fix(transformers): fix some bugs

mindone/transformers/modeling_utils.py, mindone/transformers/models/bert/modeling_bert.py
This pr is to solve loading_weight bug for ernie model. LayerNorm weight in this model has different model name (gamma-->weight/ beta --> bias) according to torch version. So key renaming mapping func should be implemented for this convertion.
@xxx
=> fix(transformers): supplement key_renaming_mapping func
